<?php
//use Recetas\Model\Funciones\Fecha;

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', '/' )
->setAttribute ( 'method', 'post' )
->setAttribute ( 'id', 'form-fe' )
->setAttribute ( 'name', 'form-fe' );
$formLabel = $this->plugin ( 'formLabel' );

$fe_rec_id = $form->get ( 'FE_REC_ID' );
$us_codigo = $form->get ( 'US_CODIGO' );
$emp_int_id = $form->get ( 'EMP_INT_ID' );
$fe_rec_tipo = $form->get ( 'FE_REC_TIPO' );
$fe_rec_idioma = $form->get ( 'FE_REC_IDIOMA' );
$ctr_fecha_creacion = $form->get ( 'CTR_FECHA_CREACION' );
//$fe_rec_responsable = $form->get ( 'FE_REC_RESPONSABLE' );
//$fe_rec_descripcion = $form->get ( 'FE_REC_DESCRIPCION' );
$fe_rec_compania = $form->get ( 'FE_REC_COMPANIA' );
$fe_rec_oferente = $form->get ( 'FE_REC_OFERENTE' );
$fe_rec_oferta_nombre = $form->get ( 'FE_REC_OFERTA_NOMBRE' );
$fe_rec_oferta_codigo = $form->get ( 'FE_REC_OFERTA_CODIGO' );
$fe_rec_fecha_hora = $form->get ( 'FE_REC_FECHA_HORA' );
$fe_rec_fecha_minuto = $form->get ( 'FE_REC_FECHA_MINUTO' );
$fe_rec_fecha = $form->get ( 'FE_REC_FECHA' );
//$fe_rec_fecha_anio = $form->get ( 'FE_REC_FECHA_ANIO' );
//$fe_rec_fecha_mes = $form->get ( 'FE_REC_FECHA_MES' );
//$fe_rec_fecha_dia = $form->get ( 'FE_REC_FECHA_DIA' );
$fe_rec_sobre = $form->get ( 'FE_REC_SOBRE' );
$fe_rec_estado = $form->get ( 'FE_REC_ESTADO' );

echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $fe_rec_id );
echo $this->formelementerrors ( $fe_rec_id );

echo $this->formhidden ( $us_codigo );
echo $this->formelementerrors ( $us_codigo );

echo $this->formhidden ( $fe_rec_estado );
echo $this->formelementerrors ( $fe_rec_estado );

echo $this->formhidden ( $ctr_fecha_creacion );
echo $this->formelementerrors ( $ctr_fecha_creacion );

?>
<ul class="error_container bs-callout bs-callout-danger">

</ul>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/recepcion_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages">Ingresar una nueva carta de fe de recepci&oacute;n</span><br />Registre toda la informaci&oacute;n solicitada para ingresar una nueva carta.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
<br />
<table width="100%" style="font-size: 13px; font-weight: 700;">
	<tr>
		<td align="center" style="padding: 20px; padding-top: 0px;">
		<div class="panel panel-default">
		<div class="panel-heading panel-heading-txt">&nbsp;</div>
			<table width="100%" cellpadding="5">
				<tr>
					<td colspan="3"><h3 align="left">Creaci&oacute;n de carta de fe de recepci&oacute;n</h3><hr /></td>
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $fe_rec_idioma->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect( $fe_rec_idioma ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_idioma ) ); 
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $emp_int_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $emp_int_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $emp_int_id ) ); 
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $fe_rec_tipo->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $fe_rec_tipo ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_tipo ) );
					?>
					</td>
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $fe_rec_compania->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $fe_rec_compania ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_compania ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $fe_rec_oferente->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $fe_rec_oferente ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_oferente ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $fe_rec_oferta_codigo->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $fe_rec_oferta_codigo ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_oferta_codigo ) );
					?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
					<?php echo $formLabel->openTag() . $fe_rec_oferta_nombre->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea ( $fe_rec_oferta_nombre ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_oferta_nombre ) );
					?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
					<table width="100%" style="border-bottom: 2px solid #D8D8D8;">
						<tr>
							<td colspan="3" align="center" style="background-color: #EEEEEE; border-right: 2px solid #D8D8D8;">Fecha de Entrega*</td>
							<td colspan="2" align="center" style="background-color: #EEEEEE;">Hora de Entrega*</td>
						</tr>
						<tr>
							<td colspan="3" style="border-right: 2px solid #D8D8D8;">
							<?php 
								  echo $formLabel->openTag() . $fe_rec_fecha->getLabel() . $formLabel->closeTag();
							      echo html_entity_decode( $this->formtext ( $fe_rec_fecha ) );
								  echo html_entity_decode( $this->formelementerrors ( $fe_rec_fecha ) ); 
							?>
							</td>
							<td style="border-right: 2px solid #D8D8D8;">
							<?php 
							echo $formLabel->openTag() . $fe_rec_fecha_hora->getLabel() . $formLabel->closeTag();
							      echo html_entity_decode( $this->formselect ( $fe_rec_fecha_hora ) );
						 		  echo html_entity_decode( $this->formelementerrors ( $fe_rec_fecha_hora ) );
							?>
							</td>
							<td>
							<?php 
							echo $formLabel->openTag() . $fe_rec_fecha_minuto->getLabel() . $formLabel->closeTag();
							      echo html_entity_decode( $this->formselect ( $fe_rec_fecha_minuto ) );
						  		  echo html_entity_decode( $this->formelementerrors ( $fe_rec_fecha_minuto ) );
							?>
							</td>
						</tr>
					</table>
					</td>
				</tr>
				<tr>
					<td colspan="3">
					<?php echo $formLabel->openTag() . $fe_rec_sobre->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea ( $fe_rec_sobre ) );
						  echo html_entity_decode( $this->formelementerrors ( $fe_rec_sobre ) );
					?>
					</td>
				</tr>
			</table>
			</div>
		</td>
	</tr>
</table>
		<div align="center">
			<?php $estado = $fe_rec_estado->getValue(); if( strtoupper($estado) != 'P' ):?>
		
			<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
			<?php echo $this->formsubmit( $form->get ( 'vista' ) ) ?>
			<?php if(strtolower($this->action) == 'editar'): ?>
			<a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'procesar', 'id' => $fe_rec_id->getValue() ))?>" class ="btn btn-primary">Procesar</a>
			<?php endif;?>
			<?php else:?>
			<a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'duplicar', 'id' => $fe_rec_id->getValue()))?>" class ="btn btn-primary">Duplicar</a>
			<?php endif; ?>
			
			
			<a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			
			
		</div>	
					
<?php echo $this->form()->closeTag(); ?>


<script>
	$(document).ready(function(){

		$("#EMP_INT_ID").change(function() {
			if($('#EMP_INT_ID').val() != '' && $('#EMP_INT_ID').val() != null){
				$.ajax({
	                url: "<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'empresaInterna')) ?>",
	                type: "POST",
	                dataType: "json",
	                data: "empresa=" + $('#EMP_INT_ID').val(),
	                beforeSend: function() {
	                	$("#FE_REC_OFERENTE").val("Procesando, espere por favor...");
	                }
	            }).done(function(empresa) {
	            		$("#FE_REC_OFERENTE").val(" " + empresa["nombre"] );
	            });
			}
        });

		//FUNCION PARA CARGAR LA FECHA DE NACIMIENTO CON UN DATEPICKER
		$( "#FE_REC_FECHA" ).datepicker({
			dateFormat:'dd-M-y',
			changeMonth: true,
			 changeYear: true,
			 yearRange: '-100:+0',
			 showOn: "button",
		            buttonImage: "<?php echo $this->basePath('img/calendar.gif')?>",
		            buttonImageOnly: true
		});

		
	});

	function habilitar(boton){
		
		var frm = document.getElementById('form-fe');
		//Ingresar - Actualizar
		if(boton == 1){
			frm.action = "<?php echo $this->url ( 'cartas', array ( 'controller' => 'recepcion', 'action' => 'validar')) ?>";
			frm.target = '_self';
		}

		//Vista Preliminar
		if(boton == 2){
			frm.action = "<?php echo $this->url ( 'cartas', array ( 'controller' => 'recepcion', 'action' => 'validarpreview')) ?>";
			frm.target = '_blank';
		}
	}
</script>