 <?php
 $title = 'Listado Fe de Recepci&oacute;n';
 $this->headTitle($title);
 ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/recepcion_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Visualizar, buscar y verificar todas las cartas "Fe de recepci&oacute;n" ingresadas en el sistema.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover " style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
     <th>TIPO</th>
     <th>IDIOMA</th>
     <th>FECHA</th>
     <th>USUARIO</th>
     <th>COMPA&Ntilde;&Iacute;A</th>
     <th>OFERENTE</th>
     <th>CODIGO FINAL</th>
     <th>FECHA Y HORA</th>
     <th>ESTADO</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->recepcion as $fe_recepcion) : ?>
 <tr>
 	 <td width="100">
 	 	<?php $carta_tipo = $fe_recepcion->getFe_rec_estado(); if(strtoupper($carta_tipo) == 'P'): ?>
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'duplicar', 'id' => $fe_recepcion->getFe_rec_id()))?>" title="Duplicar" alt="Duplicar">Duplicar</a> |
 	 	<?php else:?>
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'editar', 'id' => $fe_recepcion->getFe_rec_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<?php endif; ?>
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'recepcion', 'action' => 'pdf', 'id' => $fe_recepcion->getFe_rec_id()))?>" title="PDF" alt="PDF" target="_blank">PDF</a>
 	 </td>
	 <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_tipo());?></td>
 	 <td><?php 
     		$idioma = $fe_recepcion->getFe_rec_idioma();
     		if(strtoupper($idioma) == 'E'){ echo 'Espa&ntilde;ol'; }else{ echo 'Ingl&eacute;s'; }
     	?></td>
     <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_fecha());?></td>
     <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_responsable());?></td>
     <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_compania());?></td>
     <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_oferente());?></td>
     <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_oferta_codigo());?></td>
     <td><?php echo $this->escapeHtml($fe_recepcion->getFe_rec_fecha_anio()) . '-' . $this->escapeHtml($fe_recepcion->getFe_rec_fecha_mes()) . '-' . $this->escapeHtml($fe_recepcion->getFe_rec_fecha_dia()) . ' / ' . $this->escapeHtml($fe_recepcion->getFe_rec_fecha_hora()) . ':' . $this->escapeHtml($fe_recepcion->getFe_rec_fecha_minuto())?></td>
     <td>
     	<?php 
     	$estado = $fe_recepcion->getFe_rec_estado();
     	if(strtoupper($estado) == 'B'){ echo 'Borrador'; }else{ echo 'Procesado'; } 
     	?>
     </td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>