<?php echo $this->doctype(); ?>
<html>
    <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <?php //echo $this->headTitle('FORMULARIO DE REGISTRO') ?>
        <style>
			body, html{
				margin: 0 0;
				padding: 0 0;
				font-family: sans-serif;
				font-size:13px;
				<?php $fe_recepcion = $this->fe_recepcion['FE_REC_ESTADO']; if(strtoupper($fe_recepcion) == 'B'): ?>
				background-image: url("<?php echo $this->basepath() . '/img/jpg/borrador.jpg'?>");
				background-repeat: no-repeat;
				background-position: 0px 100px;
				<?php endif; ?>
			}
			
			.tabla_recepcion .title{
				font-weight: 700;
			}
		</style>
    </head>
    <body>
    <div style="padding-top: 200px;">&nbsp;</div>
    
    <?php $idioma = $this->fe_recepcion['FE_REC_IDIOMA']; if(strtoupper($idioma) == 'I'): ?>
    
    <table cellspacing="0" cellpadding="10" border="1" width="65%" align="center" class="tabla_recepcion">
    	<tr>
    		<td colspan="2"><span style="font-size: 40px; font-weight: 700;">Bid Submittal</span> <br /><?php //echo $this->fe_recepcion->getFe_rec_codigo_procesado()?></td>
    	</tr>
    	<tr>
    		<td class="title" width="106">Company</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_COMPANIA'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Bidder</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_OFERENTE'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Bid Description</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_OFERTA_NOMBRE'] ?></td>
    	</tr>
    	
    	<tr>
    		<td class="title">Bid Number</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_OFERTA_CODIGO'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Due Date <br/> mm/dd/yyy</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_FECHA'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Due Time</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_FECHA_HORA'] . ':' . $this->fe_recepcion['FE_REC_FECHA_MINUTO'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Bid Package Includes</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_SOBRE'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Bid</td>
    		<td>S&iacute;</td>
    	</tr>
    		<tr>
    		<td class="title" style="border: 3px solid;">Date Received by Company</td>
    		<td style="border: 3px solid;">&nbsp;</td>
    	</tr>
    	<tr>
    		<td class="title" style="border: 3px solid;">Time Received by Company</td>
    		<td style="border: 3px solid;">&nbsp;</td>
    	</tr>
    </table>
    	
    	
    <table cellspacing="0" cellpadding="10" border="1" width="65%" align="center" class="tabla_recepcion">	
    	<tr>
    		<td rowspan="2" width="20" style="border: 3px solid; border-top: 0px; " class="title">Received</td>
    		<td width="45" style="border: 3px solid; border-top: 0px; " class="title">Name</td>
    		<td style="border: 3px solid; border-top: 0px; ">&nbsp;</td>
    	</tr>
    	<tr>
    		<td style="border-right: 3px solid; border-bottom: 3px solid; " class="title">Signature</td>
    		<td style="border-right: 3px solid; border-bottom: 3px solid; ">&nbsp;</td>
    	</tr>
    </table>
    <?php else: ?>
    <table cellspacing="0" cellpadding="10" border="1" width="65%" align="center" class="tabla_recepcion">
    	<tr>
    		<td colspan="2"><span style="font-size: 40px; font-weight: 700;">Fe de Recepci&oacute;n</span> <br /><?php //echo $this->fe_recepcion->getFe_rec_codigo_procesado()?></td>
    	</tr>
    	<tr>
    		<td class="title" width="100">Empresa</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_COMPANIA'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Oferente</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_OFERENTE'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Descripci&oacute;n de la oferta</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_OFERTA_NOMBRE'] ?></td>
    	</tr>
    	
    	<tr>
    		<td class="title">C&oacute;digo de la oferta</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_OFERTA_CODIGO'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Fecha de Entrega <br/> dd/mm/yy</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_FECHA'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Hora de Entrega</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_FECHA_HORA'] . ':' . $this->fe_recepcion['FE_REC_FECHA_MINUTO']?></td>
    	</tr>
    	<tr>
    		<td class="title">Sobre de la Oferta Incluye</td>
    		<td><?php echo $this->fe_recepcion['FE_REC_SOBRE'] ?></td>
    	</tr>
    	<tr>
    		<td class="title">Oferta</td>
    		<td>S&iacute;</td>
    	</tr>
    	<tr>
    		<td class="title" style="border: 3px solid;">Fecha de Recepci&oacute;n por la Empresa</td>
    		<td style="border: 3px solid;">&nbsp;</td>
    	</tr>
    	<tr>
    		<td class="title" style="border: 3px solid;">Hora de Recepci&oacute;n por la Empresa</td>
    		<td style="border: 3px solid;">&nbsp;</td>
    	</tr>
    </table>
    <table cellspacing="0" cellpadding="10" border="1" width="65%" align="center" class="tabla_recepcion">	
    	<tr>
    		<td rowspan="2" width="41.5" style="border: 3px solid; border-top: 0px; " class="title">Recibido Por</td>
    		<td width="40" style="border: 3px solid; border-top: 0px; " class="title">Nombre</td>
    		<td style="border: 3px solid; border-top: 0px; ">&nbsp;</td>
    	</tr>
    	<tr>
    		<td style="border-right: 3px solid; border-bottom: 3px solid; " class="title">Firma</td>
    		<td style="border-right: 3px solid; border-bottom: 3px solid; ">&nbsp;</td>
    	</tr>
    </table>
    <?php endif;?>
</body>
</html>