 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Lista de Usuarios';
 $this->headTitle($title);
 ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/usuarios_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Visualizar, buscar y verificar todos los usuarios ingresados en el sistema.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>


 <p>
     <a href="<?php echo $this->url('usuarios', array('action'=>'add'));?>" class="btn btn-primary">
     	<img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Asociar Usuario
     </a>
 </p>
<div id="table">
  <table class="table table-striped table-bordered table-hover " style="font-size: 12px;" >
 	<thead>
 <tr>
 	<th>&nbsp;</th> 
     <th>Usuario</th>

        
 </tr>
</thead>
<tbody>
 <?php foreach ($usuarios as $usuario) : ?>
 <tr>
	 <td><a href='edit/<?php echo $this->escapeHtml($usuario->getUs_codigo());?>'>Editar</a></td>
     <td><?php echo $this->escapeHtml($usuario->getUs_nombre());?></td>
 </tr>
 <?php endforeach; ?>
</tbody>
 </table>
</div>
<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				},
				"aaSorting": []
			});
		});
</script>