<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/js/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/js/datatables/media/css/demo_table.css')        
                        ->prependStylesheet($this->basePath() . '/css/docs.min.css')
        				->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.4.custom.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/jquery-ui/js/jquery-ui-1.10.4.custom.min.js')
        	->prependFile($this->basePath() . '/js/typeahead.bundle.js')
        	->prependFile($this->basePath() . '/js/datatables/media/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/jquery-validation/dist/jquery.validate.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-min.js')
            ->prependFile($this->basePath() . '/js/jquery-min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    <script>

		$(document).ready(function(){
			//FUNCION PARA CARGAR EL COMBO BOX DE SUCURSALES
			$("#EMP_ID").change(function() {
				if($('#EMP_ID').val() != '' && $('#EMP_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'sucursales')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "empresa=" + $('#EMP_ID').val(),
		                beforeSend: function() {
		                	 $("#SUC_ID").html("");
		                	 $("#SUC_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(sucursales) {
		                $("#SUC_ID").html("");
		                $("#SUC_ID").append('<option value = "">-- Seleccione una sucursal --</option>');
		                var selected = '';
		                for (sucursal in sucursales) {
		                    $("#SUC_ID").append('<option value="' + sucursal + '">' + sucursales[sucursal] + '</option>');
		                }
		                $("#SUC_ID").prop("disabled", false);
		            });
				}else{
					$("#SUC_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR Y SELECCIONAR LA SUCURSAL CUANDO EL FORMULARIO ES DE ACTUALIZACION
			$("#EMP_ID").ready(function() {
			if($('#EMP_ID').val() != '' && $('#EMP_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'sucursales')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "empresa=" + $('#EMP_ID').val(),
		                beforeSend: function() {
		                	 $("#SUC_ID").html("");
		                	 $("#SUC_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(sucursales) {
		                $("#SUC_ID").html("");
		                $("#SUC_ID").append('<option value = "">-- Seleccione una sucursal --</option>');
		                for (sucursal in sucursales) {
							if(sucursal == $('#sucursal_oculto').val()){
								 var selected = 'selected="selected"';
							}
		                    $("#SUC_ID").append('<option value="' + sucursal + '" '+selected+'>' + sucursales[sucursal] + '</option>');
		                }
		                $("#SUC_ID").prop("disabled", false);
		            });
				}else{
					$("#SUC_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR EL COMBO BOX DE ESTADOS EN BASE A UN PAIS SELECCIONADO
			$("#PAI_ID").change(function() {
				if($('#PAI_ID').val() != '' && $('#PAI_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'estados')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "pais=" + $(this).val(),
		                beforeSend: function() {
		                	$("#EST_ID").html("");
		                	$("#EST_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(estados) {
		                $("#EST_ID").html("");
		                $("#EST_ID").append('<option value = "">-- Seleccione un estado --</option>');
		                for (estado in estados) {
		                    $("#EST_ID").append('<option value="' + estado + '">' + estados[estado] + '</option>');
		                }
		                $("#EST_ID").prop("disabled", false);
		            });

		            /*FUNCION PARA TRAER EL CODIGO DE PAIS A UN PAIS SELECCIONADO*/
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoPais')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "pais=" + $('#PAI_ID').val(),
		                beforeSend: function() {
		                	$("#CON_CODIGO_PAIS").val("Procesando, espere por favor...");
		                	
		                }
		            }).done(function(codigo) {
		            		$("#CON_CODIGO_PAIS").val(''+codigo['pai_codigo_telefono']);
		            });

		            
				}else{
					$("#EST_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR LOS ESTADOS CUANDO EL FORMULARIO SEA DE ACTUALIZACION
			$("#PAI_ID").ready(function() {
				if($('#PAI_ID').val() != '' && $('#PAI_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'estados')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "pais=" + $('#PAI_ID').val(),
		                beforeSend: function() {
		                	$("#EST_ID").html("");
		                	$("#EST_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(estados) {
		                $("#EST_ID").html("");
		                $("#EST_ID").append('<option value = "">-- Seleccione un estado --</option>');
		                var selected = '';
		                for (estado in estados) {

							if($("#estado_oculto").val() == estado){
								selected = 'selected="selected"';
							}else{
								selected = '';
							}
			                
		                    $("#EST_ID").append('<option value="' + estado + '" ' + selected + '>' + estados[estado] + '</option>');
		                }
		                $("#EST_ID").prop("disabled", false);
		            });
				}else{
					$("#EST_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO
			$("#EST_ID").change(function() {
				if($('#EST_ID').val() != '' && $('#EST_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'ciudades')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "estado=" + $(this).val(),
		                beforeSend: function() {
		                	$("#CIU_ID").html("");
		                	$("#CIU_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(ciudades) {
		                $("#CIU_ID").html("");
		                $("#CIU_ID").append('<option value = "">-- Seleccione una ciudad --</option>');
		                for (ciudad in ciudades) {
		                    $("#CIU_ID").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
		                }
		                $("#CIU_ID").prop("disabled", false);
		            });
				}else{
					$("#CIU_ID").prop("disabled", true);
				}
	        });

			$("#EST_ID").ready(function() {
				if($('#EST_ID').val() != '' && $('#EST_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'ciudades')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "estado=" + $('#estado_oculto').val(),
		                beforeSend: function() {
		                	$("#CIU_ID").html("");
		                	$("#CIU_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(ciudades) {
		                $("#CIU_ID").html("");
		                $("#CIU_ID").append('<option value = "">-- Seleccione una ciudad --</option>');
		                var selected = '';
		                for (ciudad in ciudades) {

		                	if($("#ciudad_oculto").val() == ciudad){
								selected = 'selected="selected"';
							}else{
								selected = '';
							}
							
		                    $("#CIU_ID").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
		                }
		                $("#CIU_ID").prop("disabled", false);
		            });
				}else{
					$("#CIU_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA TRAER EL CODIGO DE CIUDAD (TELEFONO)
			$("#CIU_ID").change(function() {
				if($('#CIU_ID').val() != '' && $('#CIU_ID').val() != null){
					
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoCiudad')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "ciudad=" + $(this).val(),
		                beforeSend: function() {
		                	$("#CON_CODIGO_CIUDAD").val("Procesando, espere por favor...");
		                }
		            }).done(function(codigo) {
		            		$("#CON_CODIGO_CIUDAD").val(''+codigo['ciu_codigo_telefono']);
		            });
				};

			});

			//FUNCION PARA CARGAR LA FECHA DE NACIMIENTO CON UN DATEPICKER
			$( "#CON_FECHA_NACIMIENTO_PERSONAL" ).datepicker({
				dateFormat:'dd-M-y',
				changeMonth: true,
				 changeYear: true,
				 yearRange: '-100:+0',
				 showOn: "button",
		                buttonImage: "<?php echo $this->basePath('img/calendar.gif')?>",
		                buttonImageOnly: true
			});
			
		});
    </script>    
        
        
    </head>
    <body>
    <div class="top-line">&nbsp;</div>
    	<table width="100%"  id="contenedor_principal" border="0">
    		<tr>
    			<td style="padding-left: 30px; padding-top: 0px;"><img id='logo' width=88 height=31 src='<?php echo $this->basePath();?>/img/logo.gif'></img></td>
    			<td align="right">
	    			<table cellspacing="0" cellpadding="0" border="0" width="35%">
						<tr>
							<td style="border-bottom: 2px solid #16ABD9; padding-bottom: 0px;">
								<div style="float: left;  padding-right: 5px; font-size: 21px; padding-top: 5px; ">
									<span style="color: #9C9FA2; padding-left: 5px;">Bienvenido: </span> 
									<img src=" <?php echo $this->basepath() . '/img/png/user.png'?>" border="0" align="absmiddle" style="padding-bottom: 0px;" />
									
								</div>
								<div class="btn-group">
									<a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="#" style="font-size: 18px; padding-left: 4px ;">Emanuel Carrasco &nbsp;<span class="caret"></span></a>
									<ul class="dropdown-menu">
										<li><a href="#"><i class="icon-pencil"></i> Actualizar contrase&ntilde;a</a></li>
										<li class="divider"></li>
										<li><a href="#"><i class="i"></i> Salir del Sistema</a></li>
									</ul>
								</div>
							</td>
						</tr>
						<tr>
							<td align="center" style="padding-top: 8px; color: #9C9FA2; font-size: 12px;"><?php date_default_timezone_set('America/Guayaquil'); echo date('l') . ', ' . date('d') . ' de ' . date('M') . ' de ' . date('Y'); ?></td>
						</tr>
					</table>
    			</td>
    		</tr>
    		<tr>
    			<td class="menu">
					<ul id="menu">
						<li><img src=" <?php echo $this->basepath() . '/img/png/home.png'?>" /> &nbsp;&nbsp;<a href="<?php echo $this->url('usuarios', array('controller' => 'index', 'action' => 'index'))?>">Inicio</a></li>
						<li><img src=" <?php echo $this->basepath() . '/img/png/contacto.png'?>" /> &nbsp;&nbsp;<a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'listado'))?>">Contactos</a></li>
						<li><img src=" <?php echo $this->basepath() . '/img/png/empresas.png'?>" /> &nbsp;&nbsp;<a href="<?php echo $this->url('empresas', array('controller' => 'index', 'action' => 'index'))?>">Empresas</a></li>
						<li><img src=" <?php echo $this->basepath() . '/img/png/correspondencia.png'?>" /> &nbsp;&nbsp;<a href="<?php echo $this->url('empresas', array('controller' => 'index', 'action' => 'index'))?>">Correspondencia</a></li>
						<li><img src=" <?php echo $this->basepath() . '/img/png/recepcion.png'?>" /> &nbsp;&nbsp;<a href="<?php echo $this->url('empresas', array('controller' => 'index', 'action' => 'index'))?>">Fe de recepci&oacute;n</a></li>
					</ul>
    			</td>
    			<td valing="top" style="padding: 30px; padding-top: 0px;">
    				<?php echo $this->content; ?>
    			</td>
    		</tr>
    		<tr>
    			<td colspan="2">
    				 <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    			</td>
    		</tr>
    	</table>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
