<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/js/datatables/media/css/demo_table.css')        
                        ->prependStylesheet($this->basePath() . '/css/docs.min.css')
        				->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.4.custom.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/typeahead.bundle.js')
        	->prependFile($this->basePath() . '/js/datatables/media/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/jquery-validation/dist/jquery.validate.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-min.js')
            ->prependFile($this->basePath() . '/js/jquery-min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    <script>

		$(document).ready(function(){
			//FUNCION PARA CARGAR EL COMBO BOX DE SUCURSALES
			$("#EMP_ID").change(function() {
				if($('#EMP_ID').val() != '' && $('#EMP_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'sucursales')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "empresa=" + $('#EMP_ID').val(),
		                beforeSend: function() {
		                	 $("#SUC_ID").html("");
		                	 $("#SUC_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(sucursales) {
		                $("#SUC_ID").html("");
		                $("#SUC_ID").append('<option>-- Seleccione una sucursal --</option>');
		                var selected = '';
		                for (sucursal in sucursales) {
		                    $("#SUC_ID").append('<option value="' + sucursal + '">' + sucursales[sucursal] + '</option>');
		                }
		                $("#SUC_ID").prop("disabled", false);
		            });
				}else{
					$("#SUC_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR Y SELECCIONAR LA SUCURSAL CUANDO EL FORMULARIO ES DE ACTUALIZACION
			$("#EMP_ID").ready(function() {
			if($('#EMP_ID').val() != '' && $('#EMP_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'sucursales')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "empresa=" + $('#EMP_ID').val(),
		                beforeSend: function() {
		                	 $("#SUC_ID").html("");
		                	 $("#SUC_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(sucursales) {
		                $("#SUC_ID").html("");
		                $("#SUC_ID").append('<option>-- Seleccione una sucursal --</option>');
		                for (sucursal in sucursales) {
							if(sucursal == $('#sucursal_oculto').val()){
								 var selected = 'selected="selected"';
							}
		                    $("#SUC_ID").append('<option value="' + sucursal + '" '+selected+'>' + sucursales[sucursal] + '</option>');
		                }
		                $("#SUC_ID").prop("disabled", false);
		            });
				}else{
					$("#SUC_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR EL COMBO BOX DE ESTADOS EN BASE A UN PAIS SELECCIONADO
			$("#PAI_ID").change(function() {
				if($('#PAI_ID').val() != '' && $('#PAI_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'estados')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "pais=" + $(this).val(),
		                beforeSend: function() {
		                	$("#EST_ID").html("");
		                	$("#EST_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(estados) {
		                $("#EST_ID").html("");
		                $("#EST_ID").append('<option>-- Seleccione un estado --</option>');
		                for (estado in estados) {
		                    $("#EST_ID").append('<option value="' + estado + '">' + estados[estado] + '</option>');
		                }
		                $("#EST_ID").prop("disabled", false);
		            });

		            /*FUNCION PARA TRAER EL CODIGO DE PAIS A UN PAIS SELECCIONADO*/
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoPais')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "pais=" + $(this).val(),
		                beforeSend: function() {
		                	$("#CON_CODIGO_PAIS").val("Procesando, espere por favor...");
		                	
		                }
		            }).done(function(codigo) {
		            		$("#CON_CODIGO_PAIS").val(''+codigo['pai_codigo_telefono']);
		            });

		            
				}else{
					$("#EST_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR LOS ESTADOS CUANDO EL FORMULARIO SEA DE ACTUALIZACION
			/*$("#PAI_ID").ready(function() {
				if($('#PAI_ID').val() != '' && $('#PAI_ID').val() != null){
			            $.ajax({
			                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'estados')) ?>",
			                type: "POST",
			                dataType: "json",
			                data: "pais=" + $('#PAI_ID').val(),
			                beforeSend: function() {
			                	 $("#EST_ID").html("");
			                	 $("#EST_ID").append('<option>Procesando, espere por favor...</option>');
			                }
			            }).done(function(estados) {
			                $("#EST_ID").html("");
			                $("#EST_ID").append('<option>-- Seleccione un estado --</option>');
			                for (estado in estados) {
								if(estado == $('#estado_oculto').val()){
									 var selected = 'selected="selected"';
								}
			                    $("#EST_ID").append('<option value="' + estado + '" '+selected+'>' + estados[estado] + '</option>');
			                }
			                $("#EST_ID").prop("disabled", false);
			            });
				}else{
					$("#EST_ID").prop("disabled", true);
				}
		    });*/

			//FUNCION PARA CARGAR EL COMBO BOX DE CIUDADES EN BASE A UN ESTADO
			$("#EST_ID").change(function() {
				if($('#EST_ID').val() != '' && $('#EST_ID').val() != null){
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'ciudades')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "estado=" + $(this).val(),
		                beforeSend: function() {
		                	$("#CIU_ID").html("");
		                	$("#CIU_ID").append('<option>Procesando, espere por favor...</option>');
		                }
		            }).done(function(ciudades) {
		                $("#CIU_ID").html("");
		                $("#CIU_ID").append('<option>-- Seleccione una ciudad --</option>');
		                for (ciudad in ciudades) {
		                    $("#CIU_ID").append('<option value="' + ciudad + '">' + ciudades[ciudad] + '</option>');
		                }
		                $("#CIU_ID").prop("disabled", false);
		            });
				}else{
					$("#CIU_ID").prop("disabled", true);
				}
	        });

			//FUNCION PARA CARGAR LAS CIUDADES CUANDO EL FORMULARIO SEA DE ACTUALIZACION
			/*$("#EST_ID").ready(function() {
				if($('#EST_ID').val() != '' && $('#EST_ID').val() != null){
			            $.ajax({
			                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'ciudades')) ?>",
			                type: "POST",
			                dataType: "json",
			                data: "estado=" + $('#estado_oculto').val(),
			                beforeSend: function() {
			                	 $("#CIU_ID").html("");
			                	 $("#CIU_ID").append('<option>Procesando, espere por favor...</option>');
			                }
			            }).done(function(ciudades) {
			                $("#CIU_ID").html("");
			                $("#CIU_ID").append('<option>-- Seleccione una ciudad --</option>');
			                for (ciudad in ciudades) {
								if(ciudad == $('#ciudad_oculto').val()){
									 var selected = 'selected="selected"';
								}
			                    $("#CIU_ID").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
			                }
			                $("#CIU_ID").prop("disabled", false);
			            });
				}else{
					$("#CIU_ID").prop("disabled", true);
				}
		    });*/

			//FUNCION PARA TRAER EL CODIGO DE CIUDAD (TELEFONO)
			$("#CIU_ID").change(function() {
				if($('#CIU_ID').val() != '' && $('#CIU_ID').val() != null){
					
		            $.ajax({
		                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoCiudad')) ?>",
		                type: "POST",
		                dataType: "json",
		                data: "ciudad=" + $(this).val(),
		                beforeSend: function() {
		                	$("#CON_CODIGO_CIUDAD").val("Procesando, espere por favor...");
		                }
		            }).done(function(codigo) {
		            		$("#CON_CODIGO_CIUDAD").val(''+codigo['ciu_codigo_telefono']);
		            });
				};

			});

			//FUNCION PARA CARGAR LA FECHA DE NACIMIENTO CON UN DATEPICKER
			$( "#CON_FECHA_NACIMIENTO_PERSONAL" ).datepicker({
				dateFormat:'dd-MM-y',
				changeMonth: true,
				 changeYear: true,
				 yearRange: '-100:+0',
				 showOn: "button",
		                buttonImage: "<?php echo $this->basePath('img/calendar.gif')?>",
		                buttonImageOnly: true
			});
			
		});
    </script>    
        
        
    </head>
    <body>
    	<table width="100%"  id="contenedor_principal">
    		<tr>
    			<td colspan="2"><img id='logo' width=88 height=31 src='<?php echo $this->basePath();?>/img/logo.gif'></img></td>
    		</tr>
    		<tr>
    			<td class="menu">
					<ul id="menu">
						<li><a href="<?php echo $this->url('usuarios', array('controller' => 'index', 'action' => 'index'))?>">Inicio</a></li>
						<li><a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'listado'))?>">Contactos</a></li>
						<li><a href="<?php echo $this->url('empresas', array('controller' => 'index', 'action' => 'index'))?>">Empresas</a></li>
					</ul>
    			</td>
    			<td><?php echo $this->content; ?></td>
    		</tr>
    		<tr>
    			<td colspan="2">
    				 <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    			</td>
    		</tr>
    	</table>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
