<?php 
use Parametros\Funciones\Funciones;
$funciones = new Funciones();
echo $this->doctype(); $idioma = $this->carta->getCtr_idioma();?>
<html>
    <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('FORMULARIO DE REGISTRO') ?>
        <style>
			body, html{
				margin: 0 0;
				padding: 0 0;
				font-family: sans-serif;
				font-size:13px;
				<?php $fe_recepcion = $this->carta->getCtr_tipo(); if(strtoupper($fe_recepcion) == 'B'): ?>
				background-image: url("<?php echo $this->basepath() . '/img/jpg/borrador.jpg'?>");
				background-repeat: no-repeat;
				background-position: 50px 100px;
				<?php endif; ?>
			}
		</style>
    </head>
    <body>
    <div style="padding-top: 130px;">&nbsp;</div>
<table cellspacing="0" cellpadding="10" border="0" width="70%" align="center">
    <tr>
        <td colspan="2">
        	<div>Quito D.M <?php echo $funciones->translateAndFormatDate($this->carta->getCtr_fecha_creacion(), $this->carta->getCtr_idioma(), 'd/m/Y')?></div>
        	<div><?php echo $this->carta->getCtr_codigo_final()?></div>
        </td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div><br />SE&Ntilde;OR / SE&Ntilde;ORES</div>
    		<div><?php echo $this->empresa->getEmp_nombre()?></div>
    		
    		<?php 
    		$mostrar = $this->carta->getCtr_activar_direccion();
    		$direccion = $this->carta->getCtr_direccion_empresa(); 
    		if(strtoupper($mostrar) == 'E'): 
    		if(empty($direccion) || is_null($direccion)):?>
    		<div><?php echo $this->empresa->getEmp_direccion()?></div>
    		<div><?php echo $this->empresa->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
    		<div><?php echo $this->empresa->getPai_nombre()?></div>
    		<?php else: ?>
    		<div><?php echo $this->direccion_e->getEmp_direccion()?></div>
    		<div><?php echo $this->direccion_e->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
    		<div><?php echo $this->direccion_e->getPai_nombre()?></div>
    		<?php endif; ?>
    		<?php elseif(strtoupper($mostrar) == 'C'): ?>
    		<div><?php echo $this->contacto->getCon_direccion()?></div>
    		<div><?php echo $this->contacto->getCiudad_nombre() . ' - ' . $this->contacto->getEstado_nombre()?></div>
    		<div><?php echo $this->contacto->getPais_nombre()?></div>
    		<?php elseif(strtoupper($mostrar) == 'N'): ?>
    		<div>&nbsp;</div>
    		<?php endif; ?>
    		
    	</td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div>
    			<br />Atenci&oacute;n: 
    			<?php if(strtoupper($idioma) == 'E'){
    				echo $this->contacto->getCon_tip_per_es();
    			}else{
    				echo $this->contacto->getCon_tip_per_en();
    			}?> 
    			<?php echo $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?> <div style="padding-left: 59px;"> 
    			<?php if(strtoupper($idioma) == 'E'){
    				echo $this->contacto->getCon_descripcion_es();
    			}else{
    				echo $this->contacto->getCon_descripcion_en();
    			}?></div></div>
    	</td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div><br /><b>Ref.: <?php echo $this->carta->getCtr_referencia()?></b></div>
    	</td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div><br /><?php echo $this->carta->getCtr_saludo()?></div>
    	</td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div style="text-align: justify;"><?php echo $this->carta->getCtr_cuerpo()?></div>
    	</td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div><br /><br /><?php echo $this->carta->getCtr_despedida()?><br /><br /></div>
    	</td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<?php foreach ($this->carta_firma as $firma): ?>
    	<td>
    		<table>
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $firma->getCar_fir_nombre() ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $firma->getCar_fir_cargo()?></td>
    			</tr>
    		</table>
    	</td>
    	<?php endforeach; ?>
    </tr>
</table>
</body>
</html>