 <?php
 $title = 'Listado de cartas';
 $this->headTitle($title);
 ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/contacto_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Visualizar, buscar y verificar todas las cartas ingresadas en el sistema.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('cartas', array('controller' => 'cartas', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover " style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
     <th>EMPRESA INTERNA</th>
     <th>TIPO DE CARTA</th>
     <th>USUARIO</th>
     <th>IDIOMA</th>
     <th>FECHA DE CREACI&Oacute;N</th>
     <th>CODIGO FINAL</th>
     <th>ESTADO</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->cartas as $carta) : ?>
 <tr>
 	 <td width="100">
 	 	<?php $ciudad = $carta->getCtr_tipo(); if(strtoupper($ciudad) == 'P'): ?>
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'cartas', 'action' => 'duplicar', 'id' => $carta->getCtr_id()))?>" title="Duplicar" alt="Duplicar">Duplicar</a> |
 	 	<?php else:?>
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'cartas', 'action' => 'editar', 'id' => $carta->getCtr_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<?php endif; ?>
 	 	
 	 	<?php if($carta->getTip_car_id() == 1):?> 
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'cartas', 'action' => 'cartaformal', 'id' => $carta->getCtr_id()))?>" title="PDF" alt="PDF">PDF</a>
 	 	<?php elseif($carta->getTip_car_id() == 2):?>
 	 	<a href="<?php echo $this->url('cartas', array('controller' => 'cartas', 'action' => 'cartainformal', 'id' => $carta->getCtr_id()))?>" title="PDF" alt="PDF">PDF</a>
 	 	<?php endif;?>
 	 	
 	 </td>
	 <td><?php echo $this->escapeHtml($carta->getEmp_int_nombre());?></td>
 	 <td><?php echo $this->escapeHtml($carta->getTip_car_descripcion());?></td>
     <td><?php echo $this->escapeHtml($carta->getUs_codigo());?></td>
     <td>
     	<?php 
     		$idioma = $carta->getCtr_idioma();
     		if(strtoupper($idioma) == 'E'){ echo 'Espa&ntilde;ol'; }else{ echo 'Ingl&eacute;s'; }
     	?>
     </td>
     <td><?php echo $this->escapeHtml($carta->getCtr_fecha_actualizacion());?></td>
     <td><?php echo $this->escapeHtml($carta->getCtr_codigo_final());?></td>
     <td>
     	<?php 
     	$ciudad = $carta->getCtr_tipo();
     	if(strtoupper($ciudad) == 'B'){ echo 'Borrador'; }else{ echo 'Procesado'; } 
     	?>
     </td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>