<?php 
use Parametros\Funciones\Funciones;
$funciones = new Funciones();
echo $this->doctype(); 
$idioma = $this->data['CTR_IDIOMA'];
?>
<html>
    <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('FORMULARIO DE REGISTRO') ?>
        <style>
			body, html{
				font-family: sans-serif;
				font-size:13px;
				<?php $fe_recepcion = $this->data['CTR_TIPO']; if(strtoupper($fe_recepcion) == 'B'): ?>
				background-image: url("<?php echo $this->basepath() . '/img/jpg/borrador.jpg'?>");
				background-repeat: no-repeat;
				background-position: 0px 100px;
				<?php endif; ?>
			}
			
			.text_cuerpo{
				width: 	80%;
				text-align: justify;
				padding-left: 80px;
				padding-top: 20px;
			}
				
			.texto_copia{
				width: 	80%;
				text-align: justify;
				padding-left: 80px;
			}
				
		</style>
    </head>
    <body>
    <?php if(strtolower($this->action) == 'cartaformalpreview'): ?>
 <!-- ###################### CARTA FORMAL ########################### -->   
    
    <div style="padding-top: 60px;">&nbsp;</div>
	<table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
   		<tr>
        	<td colspan="2">
        		<div>Quito D.M, <?php echo $funciones->translateAndFormatDate($this->data['CTR_FECHA_CREACION'], $idioma, 'd-M-Y')?></div>
        		<div><?php //echo $this->carta->getCtr_codigo_final()?></div>
        	</td>
    	</tr>
    	<tr>
	    	<td colspan="2">
	    		<div><br />SE&Ntilde;OR / SE&Ntilde;ORES</div>
	    		<div><?php echo $this->empresa->getEmp_nombre()?></div>
	    		
	    		<?php 
	    		$mostrar = $this->data['CTR_ACTIVAR_DIRECCION'];
	    		$direccion = $this->data['CTR_DIRECCION_EMPRESA']; 
	    		if(strtoupper($mostrar) == 'E'): 
	    		if(empty($direccion) || is_null($direccion)):?>
	    		<div><?php echo $this->empresa->getEmp_direccion()?></div>
	    		<div><?php echo $this->empresa->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
	    		<div><?php echo $this->empresa->getPai_nombre()?></div>
	    		<?php else: ?>
	    		<div><?php echo $this->direccion_e->getEmp_direccion()?></div>
	    		<div><?php echo $this->direccion_e->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
	    		<div><?php echo $this->direccion_e->getPai_nombre()?></div>
	    		<?php endif; ?>
	    		<?php elseif(strtoupper($mostrar) == 'C'): ?>
	    		<div><?php echo $this->contacto->getCon_direccion()?></div>
	    		<div><?php echo $this->contacto->getCiudad_nombre() . ' - ' . $this->contacto->getEstado_nombre()?></div>
	    		<div><?php echo $this->contacto->getPais_nombre()?></div>
	    		<?php elseif(strtoupper($mostrar) == 'N'): ?>
	    		<div>&nbsp;</div>
	    		<?php endif; ?>
	    	</td>
    	</tr>
    	<tr>
	    	<td colspan="2">
	    		<div>
	    			<br />Atenci&oacute;n: 
	    			<?php if(strtoupper($idioma) == 'E'){
	    				echo $this->contacto->getCon_tip_per_es();
	    			}else{
	    				echo $this->contacto->getCon_tip_per_en();
	    			}?> 
	    			<?php echo $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?> <div style="padding-left: 59px;"> 
	    			<?php if(strtoupper($idioma) == 'E'){
	    				echo $this->contacto->getCon_descripcion_es();
	    			}else{
	    				echo $this->contacto->getCon_descripcion_en();
	    			}?></div></div>
	    	</td>
    	</tr>
    	<?php $referencia = $this->data['CTR_REFERENCIA']; if(!empty($referencia) && !is_null($referencia)): ?>
    	<tr>
	    	<td colspan="2">
	    		<div><br /><b>Ref.: <?php echo $this->data['CTR_REFERENCIA']?></b></div>
	    	</td>
   		</tr>
    <?php endif;?>
    <tr>
    	<td colspan="2">
    		<div><br /><?php echo $this->data['CTR_SALUDO']?></div>
    	</td>
    </tr>
    </table>
    
    <div class="text_cuerpo">
    	<?php $cuerpo = $this->data['CTR_CUERPO'];  $salida = str_replace(array('<br />'), "<br />", $cuerpo); echo $salida;?>
    </div>
    
    <table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    <tr>
    	<td colspan="2">
    		<div><br /><br /><?php echo $this->data['CTR_DESPEDIDA']?><br /><br /></div>
    	</td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_UNO'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_UNO']?></td>
    			</tr>
    		</table>
    	</td>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_DOS'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_DOS']?></td>
    			</tr>
    		</table>
    	</td>
    </tr>
    </table>
    <?php $copia = $this->data['CTR_COPIA']; if(!empty($copia) && !is_null($copia)): ?>
    	<div class="texto_copia"><br /><br /><br /><b>CC:</b> <?php echo $copia?></div>
    <?php endif; ?>
    
    <?php $anexos = $this->data['CTR_ANEXOS']; if(!empty($anexos) && !is_null($anexos)): ?>
    	<div class="texto_copia"><br /><br /><br /><b>Anexos:</b> <br /><?php echo $anexos?><br /><br /></div>
    <?php endif; ?>
    <!-- ############################### FIN CARTA FORMAL #############################3  -->
     <?php endif;?>
     
      <?php if(strtolower($this->action) == 'cartainformalpreview'): ?>
 <!-- ###################### CARTA INFORMAL ########################### -->  
 
  <div style="padding-top: 60px;">&nbsp;</div>
<table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    <tr>
        <td colspan="2">
        	<div>Quito D.M, <?php echo $funciones->translateAndFormatDate($this->data['CTR_FECHA_CREACION'], $idioma, 'd-M-Y')?></div>
        	<div><?php //echo $this->carta->getCtr_codigo_final()?></div>
        </td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div><br />
    			<?php 
    			if(strtoupper($idioma) == 'E'){
    				echo $this->contacto->getCon_tip_per_es();
    			}else{
    				echo $this->contacto->getCon_tip_per_en();
    			}
    			?>
    		</div>
    		<div><?php echo $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?></div>
    		<div>
    			<?php 
    			if(strtoupper($idioma) == 'E'){
    				echo $this->contacto->getCon_descripcion_es();
    			}else{
    				echo $this->contacto->getCon_descripcion_en();
    			}
    			?>
    		</div>
    		<div><?php echo $this->empresa->getEmp_nombre()?></div>
    		
    		<?php $mostrar = $this->data['CTR_ACTIVAR_DIRECCION']; 
    		$direccion = $this->data['CTR_DIRECCION_EMPRESA'];
    		if(strtoupper($mostrar) == 'E'): 
    		if(empty($direccion) || is_null($direccion)):?>
    		<div><?php echo $this->empresa->getEmp_direccion()?></div>
    		<div><?php echo $this->empresa->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
    		<div><?php echo $this->empresa->getPai_nombre()?></div>
    		<?php else: ?>
    		<div><?php echo $this->direccion_e->getEmp_direccion()?></div>
    		<div><?php echo $this->direccion_e->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
    		<div><?php echo $this->direccion_e->getPai_nombre()?></div>
    		<?php endif; ?>
    		<?php elseif(strtoupper($mostrar) == 'C'): ?>
    		<div><?php echo $this->contacto->getCon_direccion()?></div>
    		<div><?php echo $this->contacto->getCiudad_nombre() . ' - ' . $this->contacto->getEstado_nombre()?></div>
    		<div><?php echo $this->contacto->getPais_nombre()?></div>
    		<?php elseif(strtoupper($mostrar) == 'N'): ?>
    		<div>&nbsp;</div>
    		<?php endif; ?>
    	</td>
    </tr>
    <?php $referencia = $this->data['CTR_REFERENCIA']; if(!empty($referencia) && !is_null($referencia)): ?>
    <tr>
    	<td colspan="2">
    		<div><br /><b>Ref.: <?php echo $referencia?></b></div>
    	</td>
    </tr>
    <?php endif;?>
    <tr>
    	<td colspan="2">
    		<div><br /><?php echo $this->data['CTR_SALUDO']?></div>
    	</td>
    </tr>
   </table>
    
     <div class="text_cuerpo">
    	<?php $cuerpo = $this->data['CTR_CUERPO'];  $salida = str_replace(array('<br />'), "<br />", $cuerpo); echo $salida;?>
    </div>
    
    <table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    <tr>
    	<td colspan="2">
    		<div><br /><br /><?php echo $this->data['CTR_DESPEDIDA']?><br /><br /></div>
    	</td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_UNO'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_UNO']?></td>
    			</tr>
    		</table>
    	</td>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_DOS'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_DOS']?></td>
    			</tr>
    		</table>
    	</td>
    </tr>
    </table>
    <?php $copia = $this->data['CTR_COPIA']; if(!empty($copia) && !is_null($copia)): ?>
    	<div class="texto_copia"><br /><br /><br /><b>CC:</b> <?php echo $copia?></div>
    <?php endif; ?>
    
    <?php $anexos = $this->data['CTR_ANEXOS']; if(!empty($anexos) && !is_null($anexos)): ?>
    	<div class="texto_copia"><br /><br /><br /><b>Anexos:</b> <br /><?php echo $anexos?><br /><br /></div>
    <?php endif; ?>
 <!-- ############################### FIN CARTA FORMAL #############################3  -->
     <?php endif;?>
     
     
     <?php if(strtolower($this->action) == 'cartafaxpreview'): ?>
 <!-- ###################### CARTA FAX  ########################### -->
 <div style="padding-left: 88px; padding-top: 60px;">
        <img src="C:\Program Files (x86)\Zend\Apache2\htdocs\Azul\Correspondencia\public\img\jpg\logo.jpg" />
        <!--<img src="C:\xampp\htdocs\correspondencia\public\img\jpg\logo.jpg" />-->
    </div>
    <div style="padding-top: 65px;">&nbsp;</div>
    
    <table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    	<tr>
    		<td colspan="2" align="right" style="font-weight: 700;">Fax: <?php //echo $this->carta->getCtr_codigo_final()?></td>
    	</tr>
    	<tr>
    		<td align="left" style="border-top: 2px solid; border-bottom: 2px solid; font-weight: 700; padding-top: 3px; padding-bottom: 5px;">Para / To</td>
    		<td align="right" style="border-top: 2px solid; border-bottom: 2px solid; font-weight: 700; padding-top: 3px; padding-bottom: 5px;">De / From</td>
    	</tr>
    	<tr>
    		<td valign="top" style="border-right: 2px solid;">
    			<table border="0" width="100%">
    				<tr>
    					<td width="100" valign="top">Compa&ntilde;&iacute;a/Company: </td>
    					<td><?php echo $this->empresa->getEmp_nombre()?> <br /><?php if(strtoupper($idioma) == 'E'){ echo $this->contacto->getCon_descripcion_es(); }else{ echo $this->contacto->getCon_descripcion_en(); }?></td>
    				</tr>
    				<tr>
    					<td>Nombre/Name:</td>
    					<td><?php if(strtoupper($idioma) == 'E'){ echo $this->contacto->getCon_tip_per_es(); }else{ echo $this->contacto->getCon_tip_per_en(); } echo $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?></td>
    				</tr>
    				<tr><td colspan="2">&nbsp;</td></tr>
    				<tr>
    					<td>Fecha/Date:</td>
    					<td><?php echo $funciones->translateAndFormatDate($this->data['CTR_FECHA_CREACION'], $idioma, 'd-M-Y')?></td>
    				</tr>
    			</table>
    		</td>
    		<td width="50%">
    			<table border="0" width="100%">
    				<tr>
    					<td align="right"><?php echo $this->data['EPL_ID_UNO'] ?> <br /><?php echo $this->data['CARGO_UNO']?></td>
    				</tr>
    				<tr>
    					<td align="right"><?php echo $this->empresa_interna->getEmp_int_direccion()?></td>
    				</tr>
    				<tr>
    					<td align="right"><?php echo $this->empresa_interna->getEmp_int_ciudad() . ', ' . $this->empresa_interna->getEmp_int_pais() ?></td>
    				</tr>
    				<tr>
    					<td align="right">PBX: <?php echo $this->empresa_interna->getEmp_int_pbx()?></td>
    				</tr>
    			</table>
    		</td>
    	</tr>
    	<?php $referencia = $this->data['CTR_REFERENCIA']; if(!empty($referencia) && !is_null($referencia)): ?>
    	<tr>
    		<td colspan="2" style="border-top: 2px solid; border-bottom: 2px solid; font-weight: 700; padding-top: 8px; padding-bottom: 8px;">Ref.: <?php echo $referencia?></td>
    	</tr>
    	<?php endif;?>
    	<tr>
    		<td colspan="2" style="margin: 0 0; padding: 0 0;">
    			<div><br /><?php echo $this->data['CTR_SALUDO']?></div>
    		</td>
   		</tr>
   	</table>
   		
   		<div class="text_cuerpo" style="padding-left: 70px;">
    		<?php $cuerpo = $this->data['CTR_CUERPO'];   $salida = str_replace(array('<br />'), "<br />", $cuerpo); echo $salida;?>
    	</div>
    	
    <table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    <tr>
    	<td colspan="2" style="margin: 0 0; padding: 0 0;">
    		<div><br /><br /><?php echo $this->data['CTR_DESPEDIDA']?><br /><br /></div>
    	</td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td width="50%" style="margin: 0 0; padding: 0 0;">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_UNO'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_UNO']?></td>
    			</tr>
    		</table>
    	</td>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_DOS'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_DOS']?></td>
    			</tr>
    		</table>
    	</td>
    </tr>
    </table>
    <?php $copia = $this->data['CTR_COPIA']; if(!empty($copia) && !is_null($copia)): ?>
    	<div class="texto_copia" style="padding-left: 70px;"><br /><br /><br /><b>CC:</b> <?php echo $copia?></div>
    <?php endif; ?>
    
    <?php $anexos = $this->data['CTR_ANEXOS']; if(!empty($anexos) && !is_null($anexos)): ?>
    	<div class="texto_copia" style="padding-left: 70px;"><br /><br /><br /><b>Anexos:</b> <br /><?php echo $anexos?><br /><br /></div>
    <?php endif; ?>
 <!-- ############################### FIN CARTA FAX #############################3  -->
     <?php endif;?>
     
     
     <?php if(strtolower($this->action) == 'cartabancariapreview'): ?>
 <!-- ###################### CARTA TRANSACCION BANCARIA  ########################### -->
 
 <div style="padding-left: 88px; padding-top: 60px;">
        <img src="C:\Program Files (x86)\Zend\Apache2\htdocs\Azul\Correspondencia\public\img\jpg\logo.jpg" />
        <!--<img src="C:\xampp\htdocs\correspondencia\public\img\jpg\logo.jpg" />-->
    </div>
    <div style="padding-top: 65px;">&nbsp;</div>
    
    <table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    	<tr>
    		<td colspan="2" align="right" style="font-weight: 700;">Fax: <?php //echo $this->carta->getCtr_codigo_final()?></td>
    	</tr>
    	<tr>
    		<td align="left" style="border-top: 2px solid; border-bottom: 2px solid; font-weight: 700; padding-top: 3px; padding-bottom: 5px;">Para / To</td>
    		<td align="right" style="border-top: 2px solid; border-bottom: 2px solid; font-weight: 700; padding-top: 3px; padding-bottom: 5px;">De / From</td>
    	</tr>
    	<tr>
    		<td valign="top" style="border-right: 2px solid;">
    			<table border="0" width="100%">
    				<tr>
    					<td width="100" valign="top">Compa&ntilde;&iacute;a/Company: </td>
    					<td><?php echo $this->empresa->getEmp_nombre()?> <br /><?php if(strtoupper($idioma) == 'E'){ echo $this->contacto->getCon_descripcion_es(); }else{ echo $this->contacto->getCon_descripcion_en(); }?></td>
    				</tr>
    				<tr>
    					<td>Nombre/Name:</td>
    					<td><?php if(strtoupper($idioma) == 'E'){ echo $this->contacto->getCon_tip_per_es(); }else{ echo $this->contacto->getCon_tip_per_en(); } echo $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?></td>
    				</tr>
    				<tr><td colspan="2">&nbsp;</td></tr>
    				<tr>
    					<td>Fecha/Date:</td>
    					<td><?php echo $funciones->translateAndFormatDate($this->data['CTR_FECHA_CREACION'], $idioma, 'd-M-Y')?></td>
    				</tr>
    			</table>
    		</td>
    		<td width="50%">
    			<table border="0" width="100%">
    				<tr>
    					<td align="right"><?php echo $this->data['EPL_ID_UNO'] ?> <br /><?php echo $this->data['CARGO_UNO'] ?></td>
    				</tr>
    				<tr>
    					<td align="right"><?php echo $this->empresa_interna->getEmp_int_direccion()?></td>
    				</tr>
    				<tr>
    					<td align="right"><?php echo $this->empresa_interna->getEmp_int_ciudad() . ', ' . $this->empresa_interna->getEmp_int_pais() ?></td>
    				</tr>
    				<tr>
    					<td align="right">PBX: <?php echo $this->empresa_interna->getEmp_int_pbx()?></td>
    				</tr>
    			</table>
    		</td>
    	</tr>
    	<?php $referencia = $this->data['CTR_REFERENCIA']; if(!empty($referencia) && !is_null($referencia)): ?>
    	<tr>
    		<td colspan="2" style="border-top: 2px solid; border-bottom: 2px solid; font-weight: 700; padding-top: 8px; padding-bottom: 8px;">Ref.: <?php echo $referencia ?></td>
    	</tr>
    	<?php endif;?>
    	<tr>
    		<td colspan="2" style="margin: 0 0; padding: 0 0;">
    			<div><br /><?php echo $this->data['CTR_SALUDO'] ?></div>
    		</td>
   		</tr>
   		</table>
   		
   		<div class="text_cuerpo" style="padding-left: 70px;" >
    		<?php $cuerpo = $this->data['CTR_CUERPO'];   $salida = str_replace(array('<br />'), "<br />", $cuerpo); echo $salida;?>
    	</div>
    	
    	<table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    	<?php  $detalle = $this->data['TRA_BAN_DETALLE']; if(strtoupper($detalle) == 'S'):?>
    	<tr>
    		<td colspan="2">
				<table width="100%" border="0">
					<tr>
						<td width="130"><b>Beneficiario: </b></td>
						<td><?php echo $this->data['TRA_BAN_BENEFICIARIO'] ?></td>
					</tr>
					<tr>
						<td><b>Direcci&oacute;n Beneficiario: </b></td>
						<td><?php echo $this->data['TRA_BAN_DIRECCION'] ?></td>
					</tr>
					<tr>
						<td><b>Cuenta No.: </b></td>
						<td><?php echo $this->data['TRA_BAN_CUENTA'] ?></td>
					</tr>
					<tr>
						<td><b>Valor: </b></td>
						<td><?php echo $this->data['TRA_BAN_VALOR'] ?></td>
					</tr>
					<tr>
						<td><b>ABA No: </b></td>
						<td><?php echo $this->data['TRA_BAN_ABA'] ?></td>
					</tr>
					<tr>
						<td><b>Nombre del Banco: </b></td>
						<td><?php echo $this->data['TRA_BAN_BANCO'] ?></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td><?php echo $this->data['TRA_BAN_BANCO_LINEA_DOS'] ?></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td><?php echo $this->data['TRA_BAN_BANCO_DIRECCION'] ?></td>
					</tr>
				</table>    		
    		</td>
    	</tr>
    	<?php endif; ?>
    	
    	
   	<tr>
    	<td colspan="2" style="margin: 0 0; padding: 0 0;">
    		<div><br /><br /><?php echo $this->data['CTR_DESPEDIDA']?><br /><br /></div>
    	</td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td width="50%" style="margin: 0 0; padding: 0 0;">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_UNO'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_UNO']?></td>
    			</tr>
    		</table>
    	</td>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_DOS'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_DOS']?></td>
    			</tr>
    		</table>
    	</td>
    </tr>
    </table>
    <?php $copia = $this->data['CTR_COPIA']; if(!empty($copia) && !is_null($copia)): ?>
    	<div class="texto_copia" style="padding-left: 70px;"><br /><br /><br /><b>CC:</b> <?php echo $copia?></div>
    <?php endif; ?>
    
    <?php $anexos = $this->data['CTR_ANEXOS']; if(!empty($anexos) && !is_null($anexos)): ?>
    	<div class="texto_copia" style="padding-left: 70px;"><br /><br /><br /><b>Anexos:</b> <br /><?php echo $anexos?><br /><br /></div>
    <?php endif; ?>
 <!-- ############################### FIN TRANSACCION BANCARIA #############################3  -->
     <?php endif;?>
     
     
          <?php if(strtolower($this->action) == 'cartasueldopreview'): ?>
 <!-- ###################### CARTA TRANSFERENCIA SUELDO  ########################### -->
 
 <div style="padding-top: 60px;">&nbsp;</div>
<table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    <tr>
        <td colspan="2">
        	<div>Quito D.M, <?php echo $funciones->translateAndFormatDate($this->data['CTR_FECHA_CREACION'], $idioma, 'd-M-Y')?></div>
        	<div><?php //echo $this->carta->getCtr_codigo_final()?></div>
        </td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div><br />Se&ntilde;or</div>
    		<div><?php echo $this->empresa->getEmp_nombre()?></div>
    		
    		<?php $mostrar = $this->data['CTR_ACTIVAR_DIRECCION']; 
    		if(strtoupper($mostrar) == 'E'): ?>
    		<div><?php echo $this->empresa->getEmp_direccion()?></div>
    		<div><?php echo $this->empresa->getCiu_nombre() . ' - ' . $this->empresa->getEst_nombre()?></div>
    		<div><?php echo $this->empresa->getPai_nombre()?></div>
    		<?php elseif(strtoupper($mostrar) == 'C'): ?>
    		<div><?php echo $this->contacto->getCon_direccion()?></div>
    		<div><?php echo $this->contacto->getCiudad_nombre() . ' - ' . $this->contacto->getEstado_nombre()?></div>
    		<div><?php echo $this->contacto->getPais_nombre()?></div>
    		<?php elseif(strtoupper($mostrar) == 'N'): ?>
    		<div>&nbsp;</div>
    		<?php endif; ?>
    		
    	</td>
    </tr>
    <tr>
    	<td colspan="2">
    		<div>
    			<br />Attn: 
    			<?php if(strtoupper($idioma) == 'E'){
    				echo $this->contacto->getCon_tip_per_es();
    			}else{
    				echo $this->contacto->getCon_tip_per_en();
    			}?> 
    			<?php echo $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?> <div style="padding-left: 59px;"> 
    			<?php 
//     			if(strtoupper($idioma) == 'E'){
//     				echo $this->contacto->getCon_descripcion_es();
//     			}else{
//     				echo $this->contacto->getCon_descripcion_en();
//     			}
    			?></div></div>
    	</td>
    </tr>
     <?php $referencia = $this->data['CTR_REFERENCIA']; if(!empty($referencia) && !is_null($referencia)): ?>
    <tr>
    	<td colspan="2">
    		<div><br /><b>Ref.: <?php echo $referencia?></b></div>
    	</td>
    </tr>
    <?php endif;?>
    <tr>
    	<td colspan="2">
    		<div><br /><?php echo $this->data['CTR_SALUDO']?></div>
    	</td>
    </tr>
    </table>
    
    <div class="text_cuerpo">
    	<?php $cuerpo = $this->data['CTR_CUERPO'];  $salida = str_replace(array('<br />'), "<br />", $cuerpo); echo $salida;?>
    </div>
    
    <table cellspacing="0" cellpadding="10" border="0" width="80%" align="center">
    <tr>
    	<td colspan="2">
    		<table width="100%" cellpadding="5" border="0" style="border: 1px solid;">
    			<tr>
    				<td width="150"><b>Valor del D&eacute;bito: </b></td>
    				<td style="border: 1px solid;"><?php echo $this->data['TRA_SUE_VALOR_DEBITO'];?></td>
    				<td>&nbsp;</td>
    			</tr>
    			<tr>
    				<td><b>N&uacute;mero de Cr&eacute;ditos: </b></td>
    				<td style="border: 1px solid;"><?php echo $this->data['TRA_SUE_NUMERO_CREDITOS'];?></td>
    				<td>&nbsp;</td>
    			</tr>
    			<tr>
    				<td><b>Valor M&aacute;ximo de Cr&eacute;dito: </b></td>
    				<td style="border: 1px solid;"><?php echo $this->data['TRA_SUE_VALOR_MAXIMO'];?></td>
    				<td>&nbsp;</td>
    			</tr>
    		</table>
    	</td>
    </tr>
    
    <tr>
    	<td colspan="2">
    		<div><br /><br /><?php echo $this->data['CTR_DESPEDIDA']?><br /><br /></div>
    	</td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_UNO'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_UNO']?></td>
    			</tr>
    		</table>
    	</td>
    	<td width="50%">
    		<table width="100%">
    			<tr>
    				<td style="text-transform: capitalize;"><?php echo $this->data['EPL_ID_DOS'] ?></td>
    			</tr>
    			<tr>
    				<td><?php echo $this->data['CARGO_DOS']?></td>
    			</tr>
    		</table>
    	</td>
    </tr>
    </table>
    <?php $copia = $this->data['CTR_COPIA']; if(!empty($copia) && !is_null($copia)): ?>
    	<div class="texto_copia"><br /><br /><br /><b>CC:</b> <?php echo $copia?></div>
    <?php endif; ?>
    
    <?php $anexos = $this->data['CTR_ANEXOS']; if(!empty($anexos) && !is_null($anexos)): ?>
    	<div class="texto_copia"><br /><br /><br /><b>Anexos:</b> <br /><?php echo $anexos?><br /><br /></div>
    <?php endif; ?>
 
  <!-- ############################### FIN TRANSFERENCIA SUELDO #############################3  -->
     <?php endif;?>
</body>
</html>