CREATE OR REPLACE FORCE VIEW PROYECTO
(PRO_ID, PRO_DESCRIPCION)
AS 
SELECT P_CODIGO AS PRO_ID, P_NOMBRE AS PRO_DESCRIPCION
FROM Vw_proyectos;


CREATE OR REPLACE FORCE VIEW VISTA_USUARIO
(US_CODIGO, US_CLAVE, US_NOMBRE)
AS 
SELECT us_codigo AS us_codigo, us_clave AS us_clave, us_nombre AS us_nombre FROM VW_USUARIO;



