<?php if(!$this->loggedIn): ?>
<?php 

$form = $this->form;
$form->prepare ()->setAttribute ( 'action', $this->url ( 'application', array (
		'controller' => 'login',
		'action' => 'autenticar'
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

echo $this->form()->openTag($form);

?>
<div class="container-main">


			<div class="usuario form-item">
			<?php 
			$email = $form->get('usu_usuario');
			echo $formLabel->openTag().$email->getOption('label');
			echo $formLabel->closeTag();
			echo $this->forminput($email);
			echo $this->formelementerrors($email);
			
			?>
			</div>

			<div class="password form-item">
			<?php 
			$password = $form->get('usu_clave');
			echo $formLabel->openTag().$password->getOption('label');
			echo $formLabel->closeTag();
			echo $this->forminput($password);
			echo $this->formelementerrors($password);
			?>
			</div>

			<div class="boton">
					<?php echo $this->formelement($form->get('ingresar')) ?>
			</div>

</div>


<?php echo $this->form()->closeTag() ?>

<?php endif; ?>