<?php if(!$this->loggedIn): ?>
<?php 

$form = $this->form;
$form->prepare ()->setAttribute ( 'action', $this->url ( 'application', array (
		'controller' => 'login',
		'action' => 'autenticar'
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

echo $this->form()->openTag($form);

?>
<div class="container">

	<div class="panel panel-default">
		<div class="panel-heading panel-heading-txt">&nbsp;</div>
		<div class="col-md-12"><h3 align="left">Ingreso</h3><hr/></div>
		<div class="row azul-form-row">
			<div class="col-md-6">
			<?php 
			$email = $form->get('usu_usuario');
			echo $formLabel->openTag().$email->getOption('label');
			echo $formLabel->closeTag();
			echo $this->forminput($email);
			echo $this->formelementerrors($email);
			
			?>
			</div>

			<div class="col-md-6">
			<?php 
			$password = $form->get('usu_clave');
			echo $formLabel->openTag().$password->getOption('label');
			echo $formLabel->closeTag();
			echo $this->forminput($password);
			echo $this->formelementerrors($password);
			?>
			</div>
		</div>
			<div class="row azul-form-row">
			<div class="col-md-12">
					<div class="col-sm-6 col-md-5 col-lg-6"><?php echo $this->formelement($form->get('ingresar')) ?></div>
			</div>
		</div>	
	</div>
</div>


<?php echo $this->form()->closeTag() ?>

<?php endif; ?>