 <?php
 $title = 'Mis Paises';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('usuarios', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($this->paises as $pais) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($pais->getPai_id());?></td>
     <td><?php echo $this->escapeHtml($pais->getPai_nombre());?></td>
     
 </tr>
 <?php endforeach; ?>
 </table>