<?php
//use Recetas\Model\Funciones\Fecha;

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'contactos', array (
		'controller' => 'index',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$con_id = $form->get ( 'CON_ID' );
$car_id = $form->get ( 'CAR_ID' );
$emp_id = $form->get ( 'EMP_ID' );
$est_id = $form->get ( 'EST_ID' );
$estado_oculto = $form->get ( 'estado_oculto' );
$suc_id = $form->get ( 'SUC_ID' );
$sucursal_oculto = $form->get ( 'sucursal_oculto' );
$tip_per_id = $form->get ( 'TIP_PER_ID' );
$pai_id = $form->get ( 'PAI_ID' );
$ciu_id = $form->get ( 'CIU_ID' );
$ciudad_oculto = $form->get ( 'ciudad_oculto' );
$con_nombre = $form->get ( 'CON_NOMBRE' );
$con_apellido = $form->get ( 'CON_APELLIDO' );
$con_email = $form->get ( 'CON_EMAIL' );
$con_idioma = $form->get ( 'CON_IDIOMA' );
$con_usuario = $form->get ( 'CON_USUARIO' );
$con_fecha_actualizacion = $form->get ( 'CON_FECHA_ACTUALIZACION' );
$con_privado = $form->get ( 'CON_PRIVADO' );
$con_fecha_personal = $form->get ( 'CON_FECHA_NACIMIENTO_PERSONAL' );
$con_email_personal = $form->get ( 'CON_EMAIL_PERSONAL' );
$con_codigo_pais = $form->get ( 'CON_CODIGO_PAIS' );
$con_codigo_ciudad = $form->get ( 'CON_CODIGO_CIUDAD' );
$con_telefono_domicilio_per = $form->get ( 'CON_TELEFONO_DOMICILIO_PER' );
$con_celular_personal = $form->get ( 'CON_CELULAR_PERSONAL' );
$con_observaciones = $form->get ( 'CON_OBSERVACIONES' );

//$date = new Fecha();

echo $this->form ()->openTag ( $form );

//CAMPOs OCULTOS
echo $this->formhidden ( $con_id );
echo $this->formelementerrors ( $con_id );

echo $this->formhidden ( $sucursal_oculto );
echo $this->formelementerrors ( $sucursal_oculto );

echo $this->formhidden ( $estado_oculto );
echo $this->formelementerrors ( $sucursal_oculto );

echo $this->formhidden ( $ciudad_oculto );
echo $this->formelementerrors ( $ciudad_oculto );
?>
<ul class="error_container bs-callout bs-callout-danger">

</ul>
<table width="100%" style="font-size: 13px; font-weight: 700;">
	<tr>
		<td align="center" style="padding: 20px; padding-top: 0px;">
		<h1 align="left">Ingresar Contacto</h1><hr />
		<div class="panel panel-default">
		<div class="panel-heading panel-heading-txt">&nbsp;</div>
			<table width="100%" cellpadding="5">
				<tr>
					<td colspan="3"><h3 align="left">Informaci&oacute;n Personal</h3><hr /></td>
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $con_idioma->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $con_idioma ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_idioma ) );
					?>
					</td>
					<td colspan="2">&nbsp;</td>		
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $tip_per_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $tip_per_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $tip_per_id ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $con_nombre->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_nombre ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_nombre ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_apellido->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_apellido ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_apellido ) );
					?>
					</td>		
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $emp_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $emp_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $emp_id ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $suc_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $suc_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $suc_id ) );
					?>
					</td>		
					<td>
					<?php echo $formLabel->openTag() . $car_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $car_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $car_id ) );
					?>
					</td>			
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $con_email->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_email ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_email ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $con_usuario->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_usuario ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_usuario ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_fecha_actualizacion->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_fecha_actualizacion ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_fecha_actualizacion ) );
					?>
					</td>
						
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $pai_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $pai_id ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $est_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $est_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $est_id ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $ciu_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $ciu_id ) );
					?>
					</td>
				</tr>
				<tr>
					<td  colspan="3">
					<?php echo $formLabel->openTag() . $con_observaciones->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea( $con_observaciones ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_observaciones ) );
					?>
					</td>
				</tr>
			</table>
			</div>
			</div>
			<div class="panel panel-default" <?php if($this->privado == 'S' && $this->tipo_usuario == 'O'){ echo 'style="display:none"'; }?>>
			<div class="panel-heading">&nbsp;</div>
			<table width="100%" cellpadding="5">				
				<tr>
					<td colspan="3"><h3 align="left">Informaci&oacute;n Privada</h3><hr /></td>
				</tr>
				<tr <?php if($this->tipo_usuario != 'A' && $this->privado == 'N'): echo 'style="display:none"'; endif;?>>
					<td>
					<?php echo $formLabel->openTag() . $con_privado->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $con_privado ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_privado ) );
					?>
					</td>
					<td colspan="2">&nbsp;</td>
				</tr>
					
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $con_email_personal->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_email_personal ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_email_personal ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $con_fecha_personal->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_fecha_personal ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_fecha_personal ) );
					?>
					</td>
					<td>&nbsp;</td>	
				</tr>
				<tr>
					<td>
						<table cellspacing="0" cellpadding="0" >
						<tr>
							<td>
								<?php echo $formLabel->openTag() . $con_codigo_pais->getLabel() . $formLabel->closeTag(); ?>
								<br />
								<?php echo html_entity_decode( $this->formtext ( $con_codigo_pais ) );
							  echo html_entity_decode( $this->formelementerrors ( $con_codigo_pais ) );
							?>
							</td>
							<td>
								<?php echo $formLabel->openTag() . $con_codigo_ciudad->getLabel() . $formLabel->closeTag(); ?>
								<br />
								<?php echo html_entity_decode( $this->formtext ( $con_codigo_ciudad ) );
							  echo html_entity_decode( $this->formelementerrors ( $con_codigo_ciudad ) );
							?>	
							</td>
						</tr>
						</table>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_telefono_domicilio_per->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_telefono_domicilio_per ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_telefono_domicilio_per ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_celular_personal->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_celular_personal ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_celular_personal ) );
					?>
					</td>		
				</tr>
			</table>
			<table width="100%" cellpadding="5">
			<tr>
				<td colspan="2">
				
				<hr />
				<h3>Otra informaci&oacute;n personal</h3>	
				<hr />
				
				</td>
			</tr>
			<?php for ( $indice_contacto_relacionado=0; $indice_contacto_relacionado<5; $indice_contacto_relacionado++ ): ?>
			<tr>
				<?php 	
					$tip_con_id = $form->get('CONTACTO_RELACIONADO['.$indice_contacto_relacionado.'][TIP_CON_ID]'); 
					$con_rel_valor = $form->get('CONTACTO_RELACIONADO['.$indice_contacto_relacionado.'][CON_REL_VALOR]');

					/* $tip_tel_id->setName('CONTACTO_RELACIONADO['.$indice_contacto_relacionado.'][TIP_CON_ID]'); 
					$det_con_codigo_pais->setName('CONTACTO_RELACIONADO['.$indice_contacto_relacionado.'][CON_REL_VALOR]');
					 */

					$tip_con_id->setAttribute('data-group-id',$indice_contacto_relacionado); 
					$con_rel_valor->setAttribute('data-group-id',$indice_contacto_relacionado);

					/* $tip_tel_id->setValue($detalle->getTip_tel_id());
					$det_con_codigo_pais->setValue($detalle->getDet_con_codigo_pais());
					$det_con_valor->setValue($detalle->getDet_con_valor());
					$det_con_extension->setValue($detalle->getDet_con_extension()); */
				?>
				<td><?php echo html_entity_decode($this->formRow($tip_con_id)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($con_rel_valor)); ?></td>
			</tr>	
		<?php endfor; ?>
		<tr>
			<td colspan="5">&nbsp;</td>
		</tr>
			</table>
			</div>
			</div>
		<div class="panel panel-default">
			<div class="panel-heading">&nbsp;</div>
<table width="100%">
				<tr>
					<td colspan="5"><h3 align="left">N&uacute;meros de Contacto</h3><hr /></td>
				</tr>
				<?php for ( $indice_detalle_contacto=0; $indice_detalle_contacto<5; $indice_detalle_contacto++ ): ?>	
				<tr>
				<?php 	
				    $det_con_oculto=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][oculto]');
					$tip_tel_id=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][TIP_TEL_ID]'); 
					$det_con_codigo_pais=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_CODIGO_PAIS]');
					$det_con_codigo_ciudad=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_CODIGO_CIUDAD]');
					$det_con_valor=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_VALOR]');
					$det_con_extension=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_EXTENSION]');

					$det_con_oculto->setAttribute('data-group-id',$indice_detalle_contacto); 
					$tip_tel_id->setAttribute('data-group-id',$indice_detalle_contacto); 
					$det_con_codigo_pais->setAttribute('data-group-id',$indice_detalle_contacto);
					$det_con_codigo_ciudad->setAttribute('data-group-id',$indice_detalle_contacto);
					$det_con_valor->setAttribute('data-group-id',$indice_detalle_contacto);
					$det_con_extension->setAttribute('data-group-id',$indice_detalle_contacto);
				?>
				<?php echo html_entity_decode($this->formhidden($det_con_oculto)); ?>
				<td><?php echo html_entity_decode($this->formRow($tip_tel_id)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_codigo_pais)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_codigo_ciudad)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_valor)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_extension)); ?></td>
			</tr>
			
		<?php endfor; ?>
		<tr>
			<td colspan="5">&nbsp;</td>
		</tr>
</table>
	</div>
	</div>
		</td>
	</tr>
</table>

	<hr />
			<div align="center">
				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				<a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			</div>	
					
<?php echo $this->form()->closeTag(); ?>

<script>

	$(document).ready(function(){

		$("#CON_IDIOMA").change(function(){
			if($("#CON_IDIOMA").val() == 'I'){
				location.href = '<?php echo $this->url('contactos',array('controller'=>'index', 'action' => $this->action, 'id' => $this->id, 'lang' => 'I'))?>';
			}else{
				location.href = '<?php echo $this->url('contactos',array('controller'=>'index', 'action' => $this->action, 'id' => $this->id, 'lang' => 'E'))?>';
			}
		});


		
		//Carga del combo box de Códigos de teléfono de Ciudades
		$(".det_con_codigo_ciudad").prop("disabled", true);

		 function codigoCiudadSelect(data_group_id,ciu_id){
			 
			$(".det_con_codigo_pais[data-group-id="+data_group_id+"]").on('change',function() {
				ajaxCiudadSelect(this,data_group_id);
	        });

			if($(".det_con_codigo_pais[data-group-id="+data_group_id+"]").val() != ''){
				ajaxCiudadSelect(".det_con_codigo_pais[data-group-id="+data_group_id+"]",data_group_id,ciu_id);	
			}
		} 

		function ajaxCiudadSelect(element,data_group_id,ciu_id){
			if($(element).val() != '' && $(element).val() != null){
	            $.ajax({
	                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoCiudadTipo')) ?>",
	                type: "POST",
	                dataType: "json",
	                data: "det_con_codigo_pais=" + $(element).val(),
	                beforeSend: function() {
	                	$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
	                	$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>Procesando, espere por favor...</option>');
	                }
	            }).done(function(ciudades) {
	                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
	                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>-- Seleccione --</option>');
	                var selected = '';
	                for (ciudad in ciudades) {
						if($('#DETALLE_CONTACTO_oculto_'+data_group_id).val() == ciudad){
							selected = 'selected="selected"';
						}
		                
	                    $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
	                }
	                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").prop("disabled", false);
	                
	            });
			}else{
				$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").prop("disabled", true);
				$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
				$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>-- Seleccione --</option>');
			}
		}

		<?php if(sizeof($detalles)<=0): for ($i=0; $i<10; $i++):?>
			codigoCiudadSelect(<?php echo $i ?>);
			
		<?php endfor; endif; ?>

	});
</script>