<?php
//use Recetas\Model\Funciones\Fecha;

$form = $this->formulario;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'contactos', array (
		'controller' => 'index',
		'action' => 'validar' 
) ) )->setAttribute ( 'method', 'post' );
$formLabel = $this->plugin ( 'formLabel' );

$con_id = $form->get ( 'CON_ID' );
$emp_id = $form->get ( 'EMP_ID' );
$est_id = $form->get ( 'EST_ID' );
$estado_oculto = $form->get ( 'estado_oculto' );
$suc_id = $form->get ( 'SUC_ID' );
$sucursal_oculto = $form->get ( 'sucursal_oculto' );
$pai_id = $form->get ( 'PAI_ID' );
$ciu_id = $form->get ( 'CIU_ID' );
$ciudad_oculto = $form->get ( 'ciudad_oculto' );
$con_nombre = $form->get ( 'CON_NOMBRE' );
$con_apellido = $form->get ( 'CON_APELLIDO' );
$con_email = $form->get ( 'CON_EMAIL' );
$con_usuario = $form->get ( 'CON_USUARIO' );
$con_fecha_actualizacion = $form->get ( 'CON_FECHA_ACTUALIZACION' );
$con_privado = $form->get ( 'CON_PRIVADO' );
$con_fecha_personal = $form->get ( 'CON_FECHA_NACIMIENTO_PERSONAL' );
$con_email_personal = $form->get ( 'CON_EMAIL_PERSONAL' );
$con_codigo_pais = $form->get ( 'CON_CODIGO_PAIS' );
$con_codigo_ciudad = $form->get ( 'CON_CODIGO_CIUDAD' );
$con_telefono_domicilio_per = $form->get ( 'CON_TELEFONO_DOMICILIO_PER' );
$con_celular_personal = $form->get ( 'CON_CELULAR_PERSONAL' );
$con_observaciones = $form->get ( 'CON_OBSERVACIONES' );
$con_descripcion_es = $form->get ( 'CON_DESCRIPCION_ES' );
$con_descripcion_en = $form->get ( 'CON_DESCRIPCION_EN' );
$con_tip_per_es = $form->get ( 'CON_TIP_PER_ES' );
$con_tip_per_en = $form->get ( 'CON_TIP_PER_EN' );

$con_direccion = $form->get ( 'CON_DIRECCION' );
$con_secretaria = $form->get ( 'CON_SECRETARIA' );
$con_secretaria_telefono = $form->get ( 'CON_SECRETARIA_TELEFONO' );
$con_direccion_domicilio_per = $form->get ( 'CON_DIRECCION_DOMICILIO_PER' );
$con_estado = $form->get ( 'CON_ESTADO' );

$con_observaciones_privado = $form->get ( 'CON_OBSERVACIONES_PRIVADO' );

//CAMPOS DE EMPRESA - NO SON PARTE DEL POST DEL FORMULARIO
$emp_direccion = $form->get ( 'EMP_DIRECCION' );
$emp_email = $form->get ( 'EMP_EMAIL' );
$emp_pagina_web = $form->get ( 'EMP_PAGINA_WEB' );

echo $this->form ()->openTag ( $form );

//CAMPOS OCULTOS
echo $this->formhidden ( $con_id );
echo $this->formelementerrors ( $con_id );

echo $this->formhidden ( $sucursal_oculto );
echo $this->formelementerrors ( $sucursal_oculto );

echo $this->formhidden ( $estado_oculto );
echo $this->formelementerrors ( $sucursal_oculto );

echo $this->formhidden ( $ciudad_oculto );
echo $this->formelementerrors ( $ciudad_oculto );

echo $this->formhidden ( $con_usuario );
echo $this->formelementerrors ( $con_usuario );

echo $this->formhidden ( $con_estado );
echo $this->formelementerrors ( $con_estado );
?>
<ul class="error_container bs-callout bs-callout-danger">

</ul>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/contacto_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages">Ingresar un nuevo contacto</span><br />Registre toda la informaci&oacute;n solicitada para ingresar un nuevo contacto.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
<br />
<table width="100%" style="font-size: 13px; font-weight: 700;">
	<tr>
		<td align="center" style="padding: 20px; padding-top: 0px;">
		<div class="panel panel-default">
		<div class="panel-heading panel-heading-txt">&nbsp;</div>
			<table width="100%" cellpadding="5">
				<tr>
					<td colspan="3"><h3 align="left">Informaci&oacute;n Personal</h3><hr /></td>
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $con_tip_per_es->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_tip_per_es ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_tip_per_es ) ); 
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_tip_per_en->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_tip_per_en ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_tip_per_en ) ); 
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_nombre->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_nombre ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_nombre ) );
					?>
					</td>
				</tr>
				<tr>
					
					<td>
					<?php echo $formLabel->openTag() . $con_apellido->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_apellido ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_apellido ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $emp_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $emp_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $emp_id ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $suc_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $suc_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $suc_id ) );
					?>
					</td>	
				</tr>
				
				<!-- CAMPOS OCULTOS DE EMPRESA -->
				<tr id="datos_empresa" style="display: none;">
					<td>
					<?php echo $formLabel->openTag() . $emp_direccion->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea ( $emp_direccion ) );
						  echo html_entity_decode( $this->formelementerrors ( $emp_direccion ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $emp_email->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $emp_email ) );
						  echo html_entity_decode( $this->formelementerrors ( $emp_email ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $emp_pagina_web->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $emp_pagina_web ) );
						  echo html_entity_decode( $this->formelementerrors ( $emp_pagina_web ) );
					?>
					</td>	
				</tr>
				<!-- FIN CAMPOS EMPRESA -->
				
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $con_descripcion_es->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_descripcion_es ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_descripcion_es ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_descripcion_en->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_descripcion_en ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_descripcion_en ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_email->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_email ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_email ) );
					?>
					</td>	
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $pai_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $pai_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $pai_id ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $est_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $est_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $est_id ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $ciu_id->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $ciu_id ) );
						  echo html_entity_decode( $this->formelementerrors ( $ciu_id ) );
					?>
					</td>
				</tr>
				<tr>
					<td>
					<?php echo $formLabel->openTag() . $con_secretaria->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_secretaria ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_secretaria ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_secretaria_telefono->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_secretaria_telefono ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_secretaria_telefono ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_fecha_actualizacion->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_fecha_actualizacion ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_fecha_actualizacion ) );
					?>
					</td>
				</tr>
				<tr>
					<td  colspan="3">
					<?php echo $formLabel->openTag() . $con_direccion->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea( $con_direccion ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_direccion ) );
					?>
					</td>
				</tr>
				<tr>
					<td  colspan="3">
					<?php echo $formLabel->openTag() . $con_observaciones->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea( $con_observaciones ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_observaciones ) );
					?>
					</td>
				</tr>
			</table>
			</div>
			</div>
			<div class="panel panel-default" <?php if($this->privado == 'S' && ($this->tipo_usuario != 1 && $this->tipo_usuario != 2)){ echo 'style="display:none"'; }?>>
			<div class="panel-heading">&nbsp;</div>
			<table width="100%" cellpadding="5">				
				<tr>
					<td colspan="3"><h3 align="left">Informaci&oacute;n Privada</h3><hr /></td>
				</tr>
				<tr <?php //if(($this->tipo_usuario != 1 && $this->tipo_usuario != 2 )&& $this->privado == 'N'): echo 'style="display:none"'; endif;?>>
					<td>
					<?php echo $formLabel->openTag() . $con_privado->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formselect ( $con_privado ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_privado ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_email_personal->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_email_personal ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_email_personal ) );
					?>
					</td>	
					<td>
					<?php echo $formLabel->openTag() . $con_fecha_personal->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_fecha_personal ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_fecha_personal ) );
					?>
					</td>
				</tr>
				<tr>
					<td>
						<table cellspacing="0" cellpadding="0" >
						<tr>
							<td>
								<?php echo $formLabel->openTag() . $con_codigo_pais->getLabel() . $formLabel->closeTag(); ?>
								<br />
								<?php echo html_entity_decode( $this->formtext ( $con_codigo_pais ) );
							  echo html_entity_decode( $this->formelementerrors ( $con_codigo_pais ) );
							?>
							</td>
							<td>
								<?php echo $formLabel->openTag() . $con_codigo_ciudad->getLabel() . $formLabel->closeTag(); ?>
								<br />
								<?php echo html_entity_decode( $this->formtext ( $con_codigo_ciudad ) );
							  echo html_entity_decode( $this->formelementerrors ( $con_codigo_ciudad ) );
							?>	
							</td>
						</tr>
						</table>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_telefono_domicilio_per->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_telefono_domicilio_per ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_telefono_domicilio_per ) );
					?>
					</td>
					<td>
					<?php echo $formLabel->openTag() . $con_celular_personal->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtext ( $con_celular_personal ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_celular_personal ) );
					?>
					</td>		
				</tr>
				<tr>
					<td  colspan="3">
					<?php echo $formLabel->openTag() . $con_direccion_domicilio_per->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea( $con_direccion_domicilio_per ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_direccion_domicilio_per ) );
					?>
					</td>
				</tr>
				<tr>
					<td  colspan="3">
					<?php echo $formLabel->openTag() . $con_observaciones_privado->getLabel() . $formLabel->closeTag();
					      echo html_entity_decode( $this->formtextarea( $con_observaciones_privado ) );
						  echo html_entity_decode( $this->formelementerrors ( $con_observaciones_privado ) );
					?>
					</td>
				</tr>
			</table>
			<table width="100%" cellpadding="5">
			<tr>
				<td colspan="2">
				
				<hr />
				<h3>Otra informaci&oacute;n personal</h3>	
				<hr />
				
				</td>
			</tr>
			<?php for ( $indice_contacto_relacionado=0; $indice_contacto_relacionado<5; $indice_contacto_relacionado++ ): ?>
			<tr>
				<?php 	
					$tip_con_id = $form->get('CONTACTO_RELACIONADO['.$indice_contacto_relacionado.'][TIP_CON_ID]'); 
					$con_rel_valor = $form->get('CONTACTO_RELACIONADO['.$indice_contacto_relacionado.'][CON_REL_VALOR]');


					$tip_con_id->setAttribute('data-group-id',$indice_contacto_relacionado); 
					$con_rel_valor->setAttribute('data-group-id',$indice_contacto_relacionado);

				?>
				<td><?php echo html_entity_decode($this->formRow($tip_con_id)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($con_rel_valor)); ?></td>
			</tr>	
		<?php endfor; ?>
		<tr>
			<td colspan="5">&nbsp;</td>
		</tr>
			</table>
			</div>
			</div>
		<div class="panel panel-default">
			<div class="panel-heading">&nbsp;</div>
<table width="100%">
				<tr>
					<td colspan="5"><h3 align="left">N&uacute;meros de Contacto</h3><hr /></td>
				</tr>
				<?php for ( $indice_detalle_contacto=0; $indice_detalle_contacto<5; $indice_detalle_contacto++ ): ?>	
				<tr>
				<?php 	
				    $det_con_oculto=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][oculto]');
					$tip_tel_id=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][TIP_TEL_ID]'); 
					$det_con_codigo_pais=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_CODIGO_PAIS]');
					$det_con_codigo_ciudad=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_CODIGO_CIUDAD]');
					$det_con_valor=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_VALOR]');
					$det_con_extension=$form->get('DETALLE_CONTACTO['.$indice_detalle_contacto.'][DET_CON_EXTENSION]');

					$det_con_oculto->setAttribute('data-group-id',$indice_detalle_contacto); 
					$tip_tel_id->setAttribute('data-group-id',$indice_detalle_contacto); 
					$det_con_codigo_pais->setAttribute('data-group-id',$indice_detalle_contacto);
					$det_con_codigo_ciudad->setAttribute('data-group-id',$indice_detalle_contacto);
					$det_con_valor->setAttribute('data-group-id',$indice_detalle_contacto);
					$det_con_extension->setAttribute('data-group-id',$indice_detalle_contacto);
				?>
				<?php echo html_entity_decode($this->formhidden($det_con_oculto)); ?>
				<td><?php echo html_entity_decode($this->formRow($tip_tel_id)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_codigo_pais)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_codigo_ciudad)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_valor)); ?></td>
				<td><?php echo html_entity_decode($this->formRow($det_con_extension)); ?></td>
			</tr>
			
		<?php endfor; ?>
		<tr>
			<td colspan="5">&nbsp;</td>
		</tr>
</table>
	</div>
	</div>
		</td>
	</tr>
</table>
	<hr />
			<div align="center">
				<?php echo $this->formsubmit( $form->get ( 'ingresar' ) ) ?>
				<a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'listado'))?>" class ="btn btn-primary">Cancelar</a>
			</div>	
					
<?php echo $this->form()->closeTag(); ?>

<script>

	$(document).ready(function(){

		/*
		$("#CON_IDIOMA").change(function(){
			if($("#CON_IDIOMA").val() == 'I'){
				location.href = '<?php //echo $this->url('contactos',array('controller'=>'index', 'action' => $this->action, 'id' => $this->id, 'lang' => 'I'))?>';
			}else{
				//location.href = '<?php //echo $this->url('contactos',array('controller'=>'index', 'action' => $this->action, 'id' => $this->id, 'lang' => 'E'))?>';
			}
		});
        */

		$('#EMP_ID').change(function(){
			if($('#EMP_ID').val() != null && $('#EMP_ID').val() != ''){

				$.ajax({
	                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'datosEmpresa')) ?>",
	                type: "POST",
	                dataType: "json",
	                data: "empresa=" + $('#EMP_ID').val(),
	                beforeSend: function() {
						$('#EMP_DIRECCION, #EMP_EMAIL, #EMP_PAGINA_WEB').val('Procesando, espere por favor...');
	                }
	            }).done(function(empresa) {
		            $('#datos_empresa').attr('style', 'display:true');
	            	$("#EMP_DIRECCION").val(''+empresa['emp_direccion']);
	            	$("#EMP_EMAIL").val(''+empresa['emp_email']);
	            	$("#EMP_PAGINA_WEB").val(''+empresa['emp_pagina_web']);
	            });
			}else{
				$('#datos_empresa').attr('style', 'display:none');
			}
		});

		$('#EMP_ID').ready(function(){
			if($('#EMP_ID').val() != null && $('#EMP_ID').val() != ''){

				$.ajax({
	                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'datosEmpresa')) ?>",
	                type: "POST",
	                dataType: "json",
	                data: "empresa=" + $('#EMP_ID').val(),
	                beforeSend: function() {
						$('#EMP_DIRECCION, #EMP_EMAIL, #EMP_PAGINA_WEB').val('Procesando, espere por favor...');
	                }
	            }).done(function(empresa) {
		            $('#datos_empresa').attr('style', 'display:true');
	            	$("#EMP_DIRECCION").val(''+empresa['emp_direccion']);
	            	$("#EMP_EMAIL").val(''+empresa['emp_email']);
	            	$("#EMP_PAGINA_WEB").val(''+empresa['emp_pagina_web']);
	            });
			}else{
				$('#datos_empresa').attr('style', 'display:none');
			}
		});
        
		
		//Carga del combo box de Códigos de teléfono de Ciudades
		$(".det_con_codigo_ciudad").prop("disabled", true);

		 function codigoCiudadSelect(data_group_id,ciu_id){
			 
			$(".det_con_codigo_pais[data-group-id="+data_group_id+"]").on('change',function() {
				ajaxCiudadSelect(this,data_group_id);
	        });

			if($(".det_con_codigo_pais[data-group-id="+data_group_id+"]").val() != ''){
				ajaxCiudadSelect(".det_con_codigo_pais[data-group-id="+data_group_id+"]",data_group_id,ciu_id);	
			}
		} 

		function ajaxCiudadSelect(element,data_group_id,ciu_id){
			if($(element).val() != '' && $(element).val() != null){
	            $.ajax({
	                url: "<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'codigoCiudadTipo')) ?>",
	                type: "POST",
	                dataType: "json",
	                data: "det_con_codigo_pais=" + $(element).val(),
	                beforeSend: function() {
	                	$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
	                	$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>Procesando, espere por favor...</option>');
	                }
	            }).done(function(ciudades) {
	                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
	                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>-- Seleccione --</option>');
	                var selected = '';
	                for (ciudad in ciudades) {
						if($('#DETALLE_CONTACTO_oculto_'+data_group_id).val() == ciudad){
							selected = 'selected="selected"';
						}
		                
	                    $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option value="' + ciudad + '" '+selected+'>' + ciudades[ciudad] + '</option>');
	                }
	                $(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").prop("disabled", false);
	                
	            });
			}else{
				$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").prop("disabled", true);
				$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").html("");
				$(".det_con_codigo_ciudad[data-group-id="+data_group_id+"]").append('<option>-- Seleccione --</option>');
			}
		}

		<?php if(sizeof($detalles)<=0): for ($i=0; $i<10; $i++):?>
			codigoCiudadSelect(<?php echo $i ?>);
			
		<?php endfor; endif; ?>

	});
</script>