 <?php
 $title = 'Contactos';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action'=>'ingresar'));?>" class="btn btn-primary">Ingresar un nuevo registro</a>
 </p>
<div style=" width:1300px; overflow: auto; padding-bottom: 100px;  ">
 <table class="table" style="width: 3000px; font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
     <th>EMPRESA</th>
     <th>SUCURSAL</th>
     <th>CARGO</th>
     <th>TIPO DE PERSONA</th>
     <th>NOMBRE</th>
     <th>APELLIDO</th>
     <th>EMAIL</th>
	 <th>PAIS</th>
	 <th>ESTADO</th>
     <th>CIUDAD</th>
     <th>IDIOMA</th>
     <th>USUARIO DE REGISTRO</th>
     <th>FECHA DE ACTUALIZACI&Oacute;N</th>
    
    <?php if(strtoupper($this->tipo_usuario) != 'O'): ?>
    
     <!-- DATOS PRIVADOS -->
     <th>&iquest;ES PRIVADO?</th>
     <th>FECHA DE NACIMIENTO</th>
     <th>DIRECCIO&Oacute;N DE DOMICILIO</th>
     <th>EMAIL PERSONAL</th>
     <th>C&Oacute;DIGO DE PA&Iacute;S</th>
     <th>C&Oacute;DIGO DE CIUDAD</th>
     <th>TEL&Eacute;FONO DE DOMICILIO</th>
     <th>CELULAR PERSONAL</th>
     <th>OBSERVACIONES</th>
     
     <?php endif; ?>
     
 </tr>
 </thead>
 <tbody>
 <?php foreach ($this->contactos as $contactos) : ?>
 <tr>
 	 <td><a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'editar', 'id' => $contactos->getCon_id(), 'lang' => $contactos->getCon_idioma()))?>" title="Actualizar" alt="Actualizar">ACT.</a></td>
     <td>
     <?php 
     
     	$empresa = $contactos->getSucursal_nombre();
     
     	if(!isset($empresa) || is_null($empresa)){
     		echo $this->escapeHtml($contactos->getEmpresa_nombre());
     	}else{
     		echo $this->escapeHtml($contactos->getSucursal_nombre());
     	}
     	?>
     
     	
     </td>
     <td><?php echo $this->escapeHtml($contactos->getEmpresa_nombre());?></td>
     <td>
     	<?php 
      		if(strtoupper($contactos->getCon_idioma()) == 'E'):
      			echo $this->escapeHtml($contactos->getCargo_descripcion_es());
      		else: 
   	  			echo $this->escapeHtml($contactos->getCargo_descripcion_en());
  			endif;
  		?>
     </td>
     <td>
    	 <?php 
      		if(strtoupper($contactos->getCon_idioma()) == 'E'):
      			echo $this->escapeHtml($contactos->getTipo_persona_descripcion_es());
      		else: 
   	  			echo $this->escapeHtml($contactos->getTipo_persona_descripcion_en());
  			endif;
  		?>
     
     </td>
     <td><?php echo $this->escapeHtml($contactos->getCon_nombre());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_apellido());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_email());?></td>
	 <td><?php echo $this->escapeHtml($contactos->getPais_nombre());?></td>
	 <td><?php echo $this->escapeHtml($contactos->getEstado_nombre());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCiudad_nombre());?></td>
     
     <td>
     	<?php
     		if(strtoupper($contactos->getCon_idioma()) == 'E'){
     			echo 'Espa&ntilde;ol';
     		}else{
     			echo 'Ingl&eacute;s';
     		}
     	?>
     </td>
     <td><?php echo $this->escapeHtml($contactos->getCon_usuario());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_fecha_actualizacion());?></td>
     
     <?php if(strtoupper($this->tipo_usuario) != 'O'): ?>
       
     <td>
     <?php if(strtoupper($contactos->getCon_privado()) == 'S'): echo 'SI'; else: echo 'NO'; endif;?>
     </td>
     <td><?php echo $this->escapeHtml($contactos->getCon_fecha_nacimiento_personal());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_direccion_domicilio_per());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_email_personal());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_codigo_pais());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_codigo_ciudad());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_telefono_domicilio_per());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_celular_personal());?></td>
     <td><?php echo $this->escapeHtml($contactos->getCon_observaciones());?></td>
     
     <?php endif; ?>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>