 <?php
 $title = 'Listado de contactos';
 $this->headTitle($title);
 ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/contacto_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Visualizar, buscar y verificar todos los contactos ingresados en el sistema.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover " style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
 	 <th>&nbsp;</th>
     <th>EMPRESA</th>
     <th>SUCURSAL</th>
     <th>CARGO</th>
     <th>TIPO DE PERSONA</th>
     <th>NOMBRE</th>
     <th>APELLIDO</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->contactos as $carta) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'editar', 'id' => $carta->getCon_id()))?>" title="Actualizar" alt="Actualizar">Editar</a>
 	 	
 	 	<?php
 	 	$activo = $carta->getCon_estado();
 	 	if(strtoupper($activo) == 'A'): ?>
 	 	| <a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'eliminar', 'id' => $carta->getCon_id()))?>" title="Dar de baja" alt="Dar de baja">Desactivar</a>
 	 	<?php else:?>
 	 		<?php if(strtoupper($this->tipo_usuario) == 'A'): ?>
 	 			| <a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'activar', 'id' => $carta->getCon_id()))?>" title="Activar" alt="Activar">Activar</a>
			<?php else:?>
				&nbsp;
 	 		<?php endif;?>
 	 	<?php endif;?>
 	 </td>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'courier', 'id' => $carta->getCon_id()))?>" title="Sobre Courier" alt="Sobre Courier" target="_blank">Courier</a> |
 	 	<a href="<?php echo $this->url('contactos', array('controller' => 'index', 'action' => 'sobre', 'id' => $carta->getCon_id()))?>" title="Sobre Nacional" alt="Sobre Nacional" target="_blank">Sobre Nacional</a>
 	 </td>
     <td>
     <?php 
     	$empresa = $carta->getSucursal_nombre();
     
     	if(!isset($empresa) || is_null($empresa)){
     		echo $this->escapeHtml($carta->getEmpresa_nombre());
     	}else{
     		echo $this->escapeHtml($carta->getSucursal_nombre());
     	}
     	?>
     </td>
     <td><?php echo $this->escapeHtml($carta->getEmpresa_nombre());?></td>
     <td><?php echo $this->escapeHtml($carta->getCon_tip_per_es());?></td>
     <td><?php echo $this->escapeHtml($carta->getCon_descripcion_es());?></td>
     <td><?php echo $this->escapeHtml($carta->getCon_nombre());?></td>
     <td><?php echo $this->escapeHtml($carta->getCon_apellido());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>