<?php echo $this->doctype(); //$idioma = $this->carta->getCtr_idioma();?>
<html>
    <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('FORMULARIO DE REGISTRO') ?>
        <style>
			body, html{
				margin: 0 0;
				padding: 0 0;
				font-family: sans-serif;
				font-size:13px;
			}
		</style>
    </head>
    <body>
    <div style="padding-top: 150px;">&nbsp;</div>
<table cellspacing="0" cellpadding="10" border="0" width="100%" align="center">
    <tr>
    	<td colspan="2" style="padding-left: 280px;">
    		<div><?php echo $this->contacto->getCon_tip_per_es() . ' ' . $this->contacto->getCon_nombre() . ' ' . $this->contacto->getCon_apellido()?></div>
    		<div><?php echo $this->contacto->getCon_descripcion_es()?></div>
    		<div><b><?php echo $this->empresa->getEmp_nombre()?></b></div>
    		<div><?php echo $this->contacto->getCon_direccion()?></div>
    		<div><?php echo $this->contacto->getCiudad_nombre() . ' - ' . $this->contacto->getEstado_nombre()?></div>
    		<div><?php echo $this->contacto->getPais_nombre()?></div>
    		<div>&nbsp;</div>
    		<?php if( $this->detalle ) :?>
    		<div>Tel: <?php echo '(' . $this->detalle->getDet_con_codigo_pais() . ' ' . $this->detalle->getDet_con_codigo_ciudad() . ') ' . $this->detalle->getDet_con_valor() . ' Ext.:' . $this->detalle->getDet_con_extension()?></div>
    		<?php endif; ?>
    	</td>
    </tr>
</table>
</body>
</html>