<h1><?php echo $this->title ?></h1>

<?php
$form = $this->form;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'empresas', array (
		'controller' => 'index',
		'action' => 'save' 
) ) );

$form->setAttribute ( 'method', 'post' );

$formLabel = $this->plugin ( 'formLabel' );

$comment=$this->comment;

echo $this->form ()->openTag ( $form );
echo $this->formHidden ( $form->get ( 'emp_id' ) );
?>

<div class="form_element">
	<div class="span-3 last">
	    <?php
			$emp_nombre = $form->get ( 'emp_nombre' );
			echo $formLabel->openTag () . $emp_nombre->getOption ( 'label' );
			echo $formLabel->closeTag ();
		?>
	</div>
	<div class="span-6 last">
		<?php 
			echo $this->formInput ( $emp_nombre );
			echo $this->formElementErrors ( $emp_nombre );
		?>
	</div>	
</div>

<?php //echo $this->formElement($form->get('send'));?>
<?php //echo $this->form()->closeTag();?>	