<h1><?php echo $this->title ?></h1>

<?php
$form = $this->form;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'empresas', array (
		'controller' => 'index',
		'action' => 'guardar' 
) ) );

$form->setAttribute ( 'method', 'post' );

$formLabel = $this->plugin ( 'formLabel' );

$comment=$this->comment;

echo $this->form ()->openTag ( $form );
?>
<?php echo $this->formRow($form->get('EMP_ID')); ?>

<?php echo $this->formRow($form->get('ESTADO_OCULTO')); ?>
<?php echo $this->formRow($form->get('CIUDAD_OCULTO')); ?>

<?php echo $this->formRow($form->get('EMP_NOMBRE')); ?>
<?php echo $this->formRow($form->get('CAT_EMP_ID')); ?>

<?php echo $this->formRow($form->get('PAI_ID')); ?>
<?php echo $this->formRow($form->get('EST_ID')); ?>
<?php echo $this->formRow($form->get('CIU_ID')); ?>

<?php echo $this->formRow($form->get('EMP_DIRECCION')); ?>
<?php echo $this->formRow($form->get('EMP_REFERENCIA')); ?>
<?php echo $this->formRow($form->get('EMP_SECTOR')); ?>
<?php echo $this->formRow($form->get('EMP_EMAIL')); ?>
<?php echo $this->formRow($form->get('EMP_PAGINA_WEB')); ?>
<?php echo $this->formRow($form->get('SUBMIT')); ?>

<?php echo $this->form()->closeTag(); ?>