 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Mis Empresas';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('empresas', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($empresas as $empresa) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($empresa->emp_id);?></td>
     <td><?php echo $this->escapeHtml($empresa->emp_nombre);?></td>
     
 </tr>
 <?php endforeach; ?>
 </table>