 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Lista de Empresas y Sucursales';
 $this->headTitle($title);
 ?>

 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/empresas_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Visualizar, buscar y verificar todas las empresas ingresadas en el sistema.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>


 <p>
     <a href="<?php echo $this->url('empresas', array('action'=>'add'));?>" class="btn btn-primary">
     	<img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar una Nueva Empresa
     </a>
 </p>
<div id="table">
  <table class="table table-striped table-bordered table-hover " style="font-size: 12px;" >
 	<thead>
 <tr>
 	<th>&nbsp;</th> 
     <th>Empresa</th>
     <th>Sucursal de</th>
     <th>Email</th>
     <th>Página Web</th>
        
 </tr>
</thead>
<tbody>
 <?php foreach ($empresas as $empresa) : ?>
 <tr>
	 <td><a href='edit/<?php echo $this->escapeHtml($empresa->emp_id);?>'>Editar</a>
	 <?php if($empresa->getEmp_estado()!='2'):  ?>
	 <span class='activar-holder' data-emp_id='<?php echo $this->escapeHtml($empresa->emp_id);?>'>
	 	 | <a 	class='desactivar' 
	 	 		href="<?php echo $this->url('empresas', array('action'=>'desactivar','id'=> $empresa->emp_id ));?>"
	 	 		data-emp_id="<?php echo $empresa->emp_id; ?>">
	 	 			Desactivar
 	 		</a>
	 </span>	
	 <?php endif; ?> 
	 </td>
     <td><?php echo $this->escapeHtml($empresa->emp_nombre);?></td>
     <td><?php echo $this->escapeHtml($empresa->padre_nombre);?></td>
     <td><?php echo $this->escapeHtml($empresa->emp_email);?></td>
     <td><?php echo $this->escapeHtml($empresa->emp_pagina_web);?></td>
 </tr>
 <?php endforeach; ?>
</tbody>
 </table>
</div>
<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				},
				"aaSorting": []
			});
			/*
			$('.desactivar').on('click',function(e){
				e.preventDefault();
				var element=$(this);
				$.ajax({
	                url: "<?php echo $this->url('empresas', array('controller' => 'empresas', 'action' => 'activar')) ?>",
	                type: "POST",
	                dataType: "json",
	                data: {emp_id:$(element).attr('data-emp_id'),emp_estado:2}
	            }).done(function(msg) {
	            	alert('test');
	                //$('.activar-holder[data-emp_id='+$(element).attr('data-emp_id')+']').hide();
	            });
	        });    */
		});
</script>