 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Mis Empresas';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('empresas', array('action'=>'add'));?>" class="btn btn-primary">Crear Nueva Empresa</a>
 </p>
<div id="table">
 <table class="table">
 	<thead>
 <tr>
     <th>Empresa</th>
     <th>Email</th>
     <th>Página Web</th>
     <th>Editar</th>    
 </tr>
</thead>
<tbody>
 <?php foreach ($empresas as $empresa) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($empresa->emp_nombre);?></td>
     <td><?php echo $this->escapeHtml($empresa->emp_email);?></td>
     <td><?php echo $this->escapeHtml($empresa->emp_pagina_web);?></td>
     <td><a href='edit/<?php echo $this->escapeHtml($empresa->emp_id);?>'>Editar</a></td>     
     
 </tr>
 <?php endforeach; ?>
</tbody>
 </table>
</div>
<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>