 <?php
 $title = 'Listado de paises';
 $this->headTitle($title);
 ?>
 <table cellspacing="0" cellpadding="0" border="0" align="left" width="100%">
	<tr>
		<td width="50" valign="middle"><img src="<?php echo $this->basepath() . '/img/png/contacto_grande.png'?>" border="0" /></td>
		<td class="titulo_menu_item_pages"><span class="titulo_modulo_pages"><?php echo $this->escapeHtml($title); ?></span><br />Visualizar, buscar y verificar todos los paises ingresados en el sistema.</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-bottom: 20px;"><hr /></td>
	</tr>
</table>
 <div style="padding-bottom: 30px;">
     <a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action'=>'ingresar'));?>" class="btn btn-primary">
     <img src="<?php echo $this->basepath() . '/img/png/ingresar.png'?>" />Ingresar un nuevo registro</a>
 </div>
<div style=" padding-bottom: 100px;  ">
 <table class="table table-striped table-bordered table-hover" style="font-size: 12px;" >
 <thead style="">
 <tr>
 	 <th>&nbsp;</th>
     <th>PA&Iacute;S</th>
     <th>C&Oacute;DIGO DE TEL&Eacute;FONO</th>
 </tr>
 </thead>
 <tbody>
 <?php 
 foreach ($this->pais as $estado) : ?>
 <tr>
 	 <td width="150">
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'editar', 'id' => $estado->getPai_id()))?>" title="Actualizar" alt="Actualizar">Editar</a> |
 	 	<a href="<?php echo $this->url('parametros', array('controller' => 'pais', 'action' => 'eliminar', 'id' => $estado->getPai_id()))?>" title="Eliminar" alt="Eliminar">Eliminar</a>
 	 </td>
     <td><?php echo $this->escapeHtml($estado->getPai_nombre());?></td>
     <td><?php echo $this->escapeHtml($estado->getPai_codigo_telefono());?></td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
</div>

<script>
		$(document).ready(function(){
			$('.table').dataTable({
				"oLanguage": {
					"sLengthMenu":     "Mostrar _MENU_  registros",
					"sInfo":           "Un total de  _TOTAL_ para mostrar (_START_ a _END_)",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sSearch":         "Buscar:",
					"oPaginate": {
						"sFirst":    "Primero",
						"sLast":     "Ultimo",
						"sNext":     "Siguiente",
						"sPrevious": "Anterior"
					}
				}
			});
		});
</script>